In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
train = pd.read_csv("labeledTrainData.tsv", delimiter = '\t', quoting = 3)
train.head()

         id  sentiment                                             review
0  "5814_8"          1  "With all this stuff going down at the moment ...
1  "2381_9"          1  "\"The Classic War of the Worlds\" by Timothy ...
2  "7759_3"          0  "The film starts with a manager (Nicholas Bell...
3  "3630_4"          0  "It must be assumed that those who praised thi...
4  "9495_8"          1  "Superbly trashy and wondrously unpretentious ...

In [4]:
#Sample Review

train["review"][0]

'"With all this stuff going down at the moment with MJ i\'ve started listening to his music, watching the odd documentary here and there, watched The Wiz and watched Moonwalker again. Maybe i just want to get a certain insight into this guy who i thought was really cool in the eighties just to maybe make up my mind whether he is guilty or innocent. Moonwalker is part biography, part feature film which i remember going to see at the cinema when it was originally released. Some of it has subtle messages about MJ\'s feeling towards the press and also the obvious message of drugs are bad m\'kay.<br /><br />Visually impressive but of course this is all about Michael Jackson so unless you remotely like MJ in anyway then you are going to hate this and find it boring. Some may call MJ an egotist for consenting to the making of this movie BUT MJ and most of his fans would say that he made it for the fans which if true is really nice of him.<br /><br />The actual feature film bit when it finally starts is only on for 20 minutes or so excluding the Smooth Criminal sequence and Joe Pesci is convincing as a psychopathic all powerful drug lord. Why he wants MJ dead so bad is beyond me. Because MJ overheard his plans? Nah, Joe Pesci\'s character ranted that he wanted people to know it is he who is supplying drugs etc so i dunno, maybe he just hates MJ\'s music.<br /><br />Lots of cool things in this like MJ turning into a car and a robot and the whole Speed Demon sequence. Also, the director must have had the patience of a saint when it came to filming the kiddy Bad sequence as usually directors hate working with one kid let alone a whole bunch of them performing a complex dance scene.<br /><br />Bottom line, this movie is for people who like MJ on one level or another (which i think is most people). If not, then stay away. It does try and give off a wholesome message and ironically MJ\'s bestest buddy in this movie is a girl! Michael Jackson is truly one of the most talented people ever to grace this planet but is he guilty? Well, with all the attention i\'ve gave this subject....hmmm well i don\'t know because people can be different behind closed doors, i know this for a fact. He is either an extremely nice but stupid guy or one of the most sickest liars. I hope he is not the latter."'

# Text Preprocessing

In [5]:
!pip install nltk
!pip install beautifulsoup4

Requirement already satisfied: nltk in c:\users\karan\anaconda3\lib\site-packages (3.9.1)
Requirement already satisfied: click in c:\users\karan\appdata\roaming\python\python313\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\users\karan\appdata\roaming\python\python313\site-packages (from nltk) (1.5.1)
Requirement already satisfied: regex>=2021.8.3 in c:\users\karan\anaconda3\lib\site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\karan\anaconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\karan\appdata\roaming\python\python313\site-packages (from click->nltk) (0.4.6)
Requirement already satisfied: beautifulsoup4 in c:\users\karan\anaconda3\lib\site-packages (4.12.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\karan\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)

In [6]:
import re
import nltk
from bs4 import BeautifulSoup

In [7]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    |
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_rus to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_rus is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package basque_grammars is already up-to-date!
[nltk_data]    | Downloading package bcp47 to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package bcp47 is already up-to-date!
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package biocreative_ppi is already up-to-date!
[nltk_data]    | Downloading package bllip_wsj_no_aux to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package bllip_wsj_no_aux is already up-to-date!
[nltk_data]    | Downloading package book_grammars to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package book_grammars is already up-to-date!
[nltk_data]    | Downloading package brown to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package brown is already up-to-date!
[nltk_data]    | Downloading package brown_tei to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package brown_tei is already up-to-date!
[nltk_data]    | Downloading package cess_cat to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package cess_cat is already up-to-date!
[nltk_data]    | Downloading package cess_esp to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package cess_esp is already up-to-date!
[nltk_data]    | Downloading package chat80 to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package chat80 is already up-to-date!
[nltk_data]    | Downloading package city_database to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package city_database is already up-to-date!
[nltk_data]    | Downloading package cmudict to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package comparative_sentences to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package comparative_sentences is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package comtrans to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package comtrans is already up-to-date!
[nltk_data]    | Downloading package conll2000 to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package conll2000 is already up-to-date!
[nltk_data]    | Downloading package conll2002 to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package conll2002 is already up-to-date!
[nltk_data]    | Downloading package conll2007 to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package conll2007 is already up-to-date!
[nltk_data]    | Downloading package crubadan to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package crubadan is already up-to-date!
[nltk_data]    | Downloading package dependency_treebank to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package dependency_treebank is already up-to-date!
[nltk_data]    | Downloading package dolch to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package dolch is already up-to-date!
[nltk_data]    | Downloading package english_wordnet to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package english_wordnet is already up-to-date!
[nltk_data]    | Downloading package europarl_raw to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package europarl_raw is already up-to-date!
[nltk_data]    | Downloading package extended_omw to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package extended_omw is already up-to-date!
[nltk_data]    | Downloading package floresta to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package floresta is already up-to-date!
[nltk_data]    | Downloading package framenet_v15 to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package framenet_v15 is already up-to-date!
[nltk_data]    | Downloading package framenet_v17 to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package framenet_v17 is already up-to-date!
[nltk_data]    | Downloading package gazetteers to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package ieer to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package ieer is already up-to-date!
[nltk_data]    | Downloading package inaugural to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package indian to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package indian is already up-to-date!
[nltk_data]    | Downloading package jeita to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package jeita is already up-to-date!
[nltk_data]    | Downloading package kimmo to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package kimmo is already up-to-date!
[nltk_data]    | Downloading package knbc to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package knbc is already up-to-date!
[nltk_data]    | Downloading package large_grammars to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package large_grammars is already up-to-date!
[nltk_data]    | Downloading package lin_thesaurus to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package lin_thesaurus is already up-to-date!
[nltk_data]    | Downloading package mac_morpho to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package mac_morpho is already up-to-date!
[nltk_data]    | Downloading package machado to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package machado is already up-to-date!
[nltk_data]    | Downloading package masc_tagged to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package masc_tagged is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package maxent_ne_chunker is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker_tab to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package maxent_ne_chunker_tab is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package maxent_treebank_pos_tagger to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package maxent_treebank_pos_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package maxent_treebank_pos_tagger_tab to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package maxent_treebank_pos_tagger_tab is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package mock_corpus to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package mock_corpus is already up-to-date!
[nltk_data]    | Downloading package moses_sample to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package moses_sample is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package mte_teip5 to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package mte_teip5 is already up-to-date!
[nltk_data]    | Downloading package mwa_ppdb to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package mwa_ppdb is already up-to-date!
[nltk_data]    | Downloading package names to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package nombank.1.0 to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package nombank.1.0 is already up-to-date!
[nltk_data]    | Downloading package nonbreaking_prefixes to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package nonbreaking_prefixes is already up-to-date!
[nltk_data]    | Downloading package nps_chat to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package nps_chat is already up-to-date!
[nltk_data]    | Downloading package omw to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package omw is already up-to-date!
[nltk_data]    | Downloading package omw-1.4 to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package opinion_lexicon to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package opinion_lexicon is already up-to-date!
[nltk_data]    | Downloading package panlex_swadesh to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package panlex_swadesh is already up-to-date!
[nltk_data]    | Downloading package paradigms to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package paradigms is already up-to-date!
[nltk_data]    | Downloading package pe08 to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package pe08 is already up-to-date!
[nltk_data]    | Downloading package perluniprops to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package perluniprops is already up-to-date!
[nltk_data]    | Downloading package pil to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package pil is already up-to-date!
[nltk_data]    | Downloading package pl196x to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package pl196x is already up-to-date!
[nltk_data]    | Downloading package porter_test to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package porter_test is already up-to-date!
[nltk_data]    | Downloading package ppattach to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package ppattach is already up-to-date!
[nltk_data]    | Downloading package problem_reports to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package problem_reports is already up-to-date!
[nltk_data]    | Downloading package product_reviews_1 to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package product_reviews_1 is already up-to-date!
[nltk_data]    | Downloading package product_reviews_2 to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package product_reviews_2 is already up-to-date!
[nltk_data]    | Downloading package propbank to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package propbank is already up-to-date!
[nltk_data]    | Downloading package pros_cons to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package pros_cons is already up-to-date!
[nltk_data]    | Downloading package ptb to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package ptb is already up-to-date!
[nltk_data]    | Downloading package punkt to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package punkt_tab to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package punkt_tab is already up-to-date!
[nltk_data]    | Downloading package qc to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package qc is already up-to-date!
[nltk_data]    | Downloading package reuters to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package reuters is already up-to-date!
[nltk_data]    | Downloading package rslp to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package rslp is already up-to-date!
[nltk_data]    | Downloading package rte to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package rte is already up-to-date!
[nltk_data]    | Downloading package sample_grammars to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package sample_grammars is already up-to-date!
[nltk_data]    | Downloading package semcor to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package semcor is already up-to-date!
[nltk_data]    | Downloading package senseval to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package senseval is already up-to-date!
[nltk_data]    | Downloading package sentence_polarity to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package sentence_polarity is already up-to-date!
[nltk_data]    | Downloading package sentiwordnet to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package sentiwordnet is already up-to-date!
[nltk_data]    | Downloading package shakespeare to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package shakespeare is already up-to-date!
[nltk_data]    | Downloading package sinica_treebank to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package sinica_treebank is already up-to-date!
[nltk_data]    | Downloading package smultron to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package smultron is already up-to-date!
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package snowball_data is already up-to-date!
[nltk_data]    | Downloading package spanish_grammars to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package spanish_grammars is already up-to-date!
[nltk_data]    | Downloading package state_union to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package state_union is already up-to-date!
[nltk_data]    | Downloading package stopwords to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package subjectivity to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package subjectivity is already up-to-date!
[nltk_data]    | Downloading package swadesh to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package swadesh is already up-to-date!
[nltk_data]    | Downloading package switchboard to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package switchboard is already up-to-date!
[nltk_data]    | Downloading package tagsets to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package tagsets is already up-to-date!
[nltk_data]    | Downloading package tagsets_json to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package tagsets_json is already up-to-date!
[nltk_data]    | Downloading package timit to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package timit is already up-to-date!
[nltk_data]    | Downloading package toolbox to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package toolbox is already up-to-date!
[nltk_data]    | Downloading package treebank to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package treebank is already up-to-date!
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package twitter_samples is already up-to-date!
[nltk_data]    | Downloading package udhr to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package udhr is already up-to-date!
[nltk_data]    | Downloading package udhr2 to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package udhr2 is already up-to-date!
[nltk_data]    | Downloading package unicode_samples to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package unicode_samples is already up-to-date!
[nltk_data]    | Downloading package universal_tagset to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package universal_tagset is already up-to-date!
[nltk_data]    | Downloading package universal_treebanks_v20 to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package universal_treebanks_v20 is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package vader_lexicon to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package vader_lexicon is already up-to-date!
[nltk_data]    | Downloading package verbnet to
[nltk_data]    |     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]    |   Package verbnet is already up-to-date!

True

In [8]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [9]:
stopwords = stopwords.words("english")
wordnet_lemma = WordNetLemmatizer()

In [10]:
review = train['review'][0]
review

'"With all this stuff going down at the moment with MJ i\'ve started listening to his music, watching the odd documentary here and there, watched The Wiz and watched Moonwalker again. Maybe i just want to get a certain insight into this guy who i thought was really cool in the eighties just to maybe make up my mind whether he is guilty or innocent. Moonwalker is part biography, part feature film which i remember going to see at the cinema when it was originally released. Some of it has subtle messages about MJ\'s feeling towards the press and also the obvious message of drugs are bad m\'kay.<br /><br />Visually impressive but of course this is all about Michael Jackson so unless you remotely like MJ in anyway then you are going to hate this and find it boring. Some may call MJ an egotist for consenting to the making of this movie BUT MJ and most of his fans would say that he made it for the fans which if true is really nice of him.<br /><br />The actual feature film bit when it finally starts is only on for 20 minutes or so excluding the Smooth Criminal sequence and Joe Pesci is convincing as a psychopathic all powerful drug lord. Why he wants MJ dead so bad is beyond me. Because MJ overheard his plans? Nah, Joe Pesci\'s character ranted that he wanted people to know it is he who is supplying drugs etc so i dunno, maybe he just hates MJ\'s music.<br /><br />Lots of cool things in this like MJ turning into a car and a robot and the whole Speed Demon sequence. Also, the director must have had the patience of a saint when it came to filming the kiddy Bad sequence as usually directors hate working with one kid let alone a whole bunch of them performing a complex dance scene.<br /><br />Bottom line, this movie is for people who like MJ on one level or another (which i think is most people). If not, then stay away. It does try and give off a wholesome message and ironically MJ\'s bestest buddy in this movie is a girl! Michael Jackson is truly one of the most talented people ever to grace this planet but is he guilty? Well, with all the attention i\'ve gave this subject....hmmm well i don\'t know because people can be different behind closed doors, i know this for a fact. He is either an extremely nice but stupid guy or one of the most sickest liars. I hope he is not the latter."'

In [11]:
def preprocess_text(review): 
    # Removing all the HTML Tags
    review = BeautifulSoup(review).get_text()
    
    # Remove anything which is not a character
    review = re.sub( "[^a-zA-Z]", " ", review)
    
    # Lowercasing 
    review = review.lower()
    
    # Remove Stopwords
    review = " ".join([i for i in review.split() if i not in stopwords])
    
    # Lemmatizer
    review = " ".join([wordnet_lemma.lemmatize(i) for i in review.split()])

    return review

In [12]:
review = train['review'][0]
print('Original Text')
print(review)
print('-'*50)
cleaned_review = preprocess_text(review)
print('Cleaned Text')
print(cleaned_review)

Original Text
"With all this stuff going down at the moment with MJ i've started listening to his music, watching the odd documentary here and there, watched The Wiz and watched Moonwalker again. Maybe i just want to get a certain insight into this guy who i thought was really cool in the eighties just to maybe make up my mind whether he is guilty or innocent. Moonwalker is part biography, part feature film which i remember going to see at the cinema when it was originally released. Some of it has subtle messages about MJ's feeling towards the press and also the obvious message of drugs are bad m'kay.<br /><br />Visually impressive but of course this is all about Michael Jackson so unless you remotely like MJ in anyway then you are going to hate this and find it boring. Some may call MJ an egotist for consenting to the making of this movie BUT MJ and most of his fans would say that he made it for the fans which if true is really nice of him.<br /><br />The actual feature film bit when it finally starts is only on for 20 minutes or so excluding the Smooth Criminal sequence and Joe Pesci is convincing as a psychopathic all powerful drug lord. Why he wants MJ dead so bad is beyond me. Because MJ overheard his plans? Nah, Joe Pesci's character ranted that he wanted people to know it is he who is supplying drugs etc so i dunno, maybe he just hates MJ's music.<br /><br />Lots of cool things in this like MJ turning into a car and a robot and the whole Speed Demon sequence. Also, the director must have had the patience of a saint when it came to filming the kiddy Bad sequence as usually directors hate working with one kid let alone a whole bunch of them performing a complex dance scene.<br /><br />Bottom line, this movie is for people who like MJ on one level or another (which i think is most people). If not, then stay away. It does try and give off a wholesome message and ironically MJ's bestest buddy in this movie is a girl! Michael Jackson is truly one of the most talented people ever to grace this planet but is he guilty? Well, with all the attention i've gave this subject....hmmm well i don't know because people can be different behind closed doors, i know this for a fact. He is either an extremely nice but stupid guy or one of the most sickest liars. I hope he is not the latter."
--------------------------------------------------
Cleaned Text
stuff going moment mj started listening music watching odd documentary watched wiz watched moonwalker maybe want get certain insight guy thought really cool eighty maybe make mind whether guilty innocent moonwalker part biography part feature film remember going see cinema originally released subtle message mj feeling towards press also obvious message drug bad kay visually impressive course michael jackson unless remotely like mj anyway going hate find boring may call mj egotist consenting making movie mj fan would say made fan true really nice actual feature film bit finally start minute excluding smooth criminal sequence joe pesci convincing psychopathic powerful drug lord want mj dead bad beyond mj overheard plan nah joe pesci character ranted wanted people know supplying drug etc dunno maybe hate mj music lot cool thing like mj turning car robot whole speed demon sequence also director must patience saint came filming kiddy bad sequence usually director hate working one kid let alone whole bunch performing complex dance scene bottom line movie people like mj one level another think people stay away try give wholesome message ironically mj bestest buddy movie girl michael jackson truly one talented people ever grace planet guilty well attention gave subject hmmm well know people different behind closed door know fact either extremely nice stupid guy one sickest liar hope latter

In [13]:
# Apply this function over full DataFrame
train['clean_review'] = train['review'].apply(preprocess_text)
train.head()

C:\Users\karan\AppData\Local\Temp\ipykernel_25548\3404633976.py:3: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  review = BeautifulSoup(review).get_text()

,id,sentiment,review,clean_review
0,"""5814_8""",1,"""With all this stuff going down at the moment ...",stuff going moment mj started listening music ...
1,"""2381_9""",1,"""\""The Classic War of the Worlds\"" by Timothy ...",classic war world timothy hines entertaining f...
2,"""7759_3""",0,"""The film starts with a manager (Nicholas Bell...",film start manager nicholas bell giving welcom...
3,"""3630_4""",0,"""It must be assumed that those who praised thi...",must assumed praised film greatest filmed oper...
4,"""9495_8""",1,"""Superbly trashy and wondrously unpretentious ...",superbly trashy wondrously unpretentious explo...

In [14]:
# List of all words Frequency.
freq_list = {}

for review in train['clean_review'].tolist():
    for word in review.split():
        freq_list[word] = freq_list.get(word, 0)+1

In [15]:
freq_list

{'stuff': 1181,
 'going': 4146,
 'moment': 2775,
 'mj': 35,
 'started': 963,
 'listening': 189,
 'music': 3061,
 'watching': 4605,
 'odd': 582,
 'documentary': 1074,
 'watched': 2236,
 'wiz': 11,
 'moonwalker': 24,
 'maybe': 2340,
 'want': 4990,
 'get': 12514,
 'certain': 764,
 'insight': 250,
 'guy': 4339,
 'thought': 3656,
 'really': 11736,
 'cool': 971,
 'eighty': 127,
 'make': 12225,
 'mind': 2180,
 'whether': 856,
 'guilty': 198,
 'innocent': 434,
 'part': 5233,
 'biography': 99,
 'feature': 1434,
 'film': 47034,
 'remember': 1702,
 'see': 12012,
 'cinema': 1553,
 'originally': 290,
 'released': 986,
 'subtle': 434,
 'message': 960,
 'feeling': 1540,
 'towards': 637,
 'press': 134,
 'also': 9156,
 'obvious': 1066,
 'drug': 728,
 'bad': 9302,
 'kay': 91,
 'visually': 259,
 'impressive': 500,
 'course': 2517,
 'michael': 1370,
 'jackson': 346,
 'unless': 675,
 'remotely': 189,
 'like': 20740,
 'anyway': 1117,
 'hate': 893,
 'find': 5079,
 'boring': 1809,
 'may': 3392,
 'call': 1183,
 'egotist': 5,
 'consenting': 5,
 'making': 2978,
 'movie': 51694,
 'fan': 3332,
 'would': 12436,
 'say': 6505,
 'made': 8362,
 'true': 2333,
 'nice': 2012,
 'actual': 793,
 'bit': 3349,
 'finally': 1536,
 'start': 2920,
 'minute': 3741,
 'excluding': 14,
 'smooth': 129,
 'criminal': 499,
 'sequence': 1603,
 'joe': 690,
 'pesci': 29,
 'convincing': 538,
 'psychopathic': 23,
 'powerful': 620,
 'lord': 373,
 'dead': 1881,
 'beyond': 866,
 'overheard': 7,
 'plan': 625,
 'nah': 18,
 'character': 14177,
 'ranted': 4,
 'wanted': 1352,
 'people': 9385,
 'know': 7067,
 'supplying': 10,
 'etc': 1212,
 'dunno': 24,
 'lot': 4778,
 'thing': 8214,
 'turning': 345,
 'car': 1504,
 'robot': 329,
 'whole': 3079,
 'speed': 266,
 'demon': 375,
 'director': 5119,
 'must': 3250,
 'patience': 81,
 'saint': 117,
 'came': 1673,
 'filming': 393,
 'kiddy': 28,
 'usually': 981,
 'working': 817,
 'one': 27741,
 'kid': 3043,
 'let': 2675,
 'alone': 1061,
 'bunch': 817,
 'performing': 131,
 'complex': 429,
 'dance': 847,
 'scene': 10585,
 'bottom': 433,
 'line': 3422,
 'level': 1198,
 'another': 4325,
 'think': 7733,
 'stay': 969,
 'away': 2775,
 'try': 3109,
 'give': 4952,
 'wholesome': 45,
 'ironically': 123,
 'bestest': 2,
 'buddy': 367,
 'girl': 4064,
 'truly': 1743,
 'talented': 586,
 'ever': 5995,
 'grace': 358,
 'planet': 534,
 'well': 10783,
 'attention': 929,
 'gave': 1216,
 'subject': 816,
 'hmmm': 50,
 'different': 2385,
 'behind': 1280,
 'closed': 92,
 'door': 557,
 'fact': 3747,
 'either': 1866,
 'extremely': 1069,
 'stupid': 1701,
 'sickest': 10,
 'liar': 48,
 'hope': 1720,
 'latter': 362,
 'classic': 2061,
 'war': 2383,
 'world': 3978,
 'timothy': 118,
 'hines': 48,
 'entertaining': 1442,
 'obviously': 1163,
 'go': 7600,
 'great': 9088,
 'effort': 1046,
 'length': 361,
 'faithfully': 22,
 'recreate': 35,
 'h': 293,
 'g': 484,
 'book': 2926,
 'mr': 1708,
 'succeeds': 167,
 'appreciated': 196,
 'standard': 803,
 'predictable': 854,
 'hollywood': 1911,
 'fare': 226,
 'come': 5673,
 'every': 3978,
 'year': 6878,
 'e': 825,
 'spielberg': 154,
 'version': 2410,
 'tom': 785,
 'cruise': 134,
 'slightest': 122,
 'resemblance': 115,
 'everyone': 2222,
 'look': 6558,
 'envision': 9,
 'amateur': 246,
 'critic': 522,
 'criticize': 51,
 'everything': 2321,
 'others': 1595,
 'rate': 704,
 'important': 931,
 'base': 198,
 'entertained': 237,
 'never': 6484,
 'agree': 572,
 'enjoyed': 1245,
 'put': 2760,
 'faithful': 178,
 'novel': 1126,
 'found': 2576,
 'easy': 802,
 'overlook': 92,
 'perceive': 34,
 'shortcoming': 77,
 'manager': 168,
 'nicholas': 92,
 'bell': 136,
 'giving': 840,
 'welcome': 226,
 'investor': 14,
 'robert': 1093,
 'carradine': 94,
 'primal': 32,
 'park': 411,
 'secret': 724,
 'project': 623,
 'mutating': 2,
 'animal': 752,
 'using': 801,
 'fossilized': 1,
 'dna': 24,
 'jurassik': 2,
 'scientist': 477,
 'resurrect': 24,
 'nature': 723,
 'fearsome': 10,
 'predator': 72,
 'sabretooth': 31,
 'tiger': 109,
 'smilodon': 3,
 'scientific': 119,
 'ambition': 118,
 'turn': 2610,
 'deadly': 201,
 'however': 3537,
 'high': 2174,
 'voltage': 9,
 'fence': 50,
 'opened': 155,
 'creature': 554,
 'escape': 701,
 'begin': 1473,
 'savagely': 17,
 'stalking': 62,
 'prey': 82,
 'human': 1915,
 'visitor': 77,
 'tourist': 91,
 'meanwhile': 249,
 'youngster': 57,
 'enter': 196,
 'restricted': 27,
 'area': 453,
 'security': 195,
 'center': 323,
 'attacked': 158,
 'pack': 210,
 'large': 556,
 'pre': 309,
 'historical': 407,
 'deadlier': 2,
 'bigger': 268,
 'addition': 371,
 'agent': 455,
 'stacy': 21,
 'haiduk': 2,
 'mate': 183,
 'brian': 352,
 'wimmer': 2,
 'fight': 1433,
 'hardly': 613,
 'carnivorous': 7,
 'smilodons': 1,
 'sabretooths': 7,
 'real': 4738,
 'star': 3782,
 'astounding': 59,
 'terrifyingly': 13,
 'though': 4566,
 'giant': 440,
 'group': 1142,
 'run': 1731,
 'afoul': 13,
 'furthermore': 106,
 'third': 776,
 'dangerous': 291,
 'slow': 1131,
 'stalk': 66,
 'victim': 793,
 'delivers': 356,
 'good': 15197,
 'blood': 1186,
 'gore': 1040,
 'beheading': 16,
 'hair': 519,
 'raising': 94,
 'chill': 130,
 'full': 1780,
 'scare': 408,
 'appear': 619,
 'mediocre': 365,
 'special': 2135,
 'effect': 2837,
 'story': 13165,
 'provides': 350,
 'exciting': 515,
 'stirring': 41,
 'entertainment': 887,
 'result': 906,
 'quite': 3738,
 'majority': 238,
 'computer': 534,
 'generator': 12,
 'seem': 2175,
 'totally': 1307,
 'lousy': 220,
 'middling': 11,
 'performance': 4717,
 'player': 586,
 'reacting': 21,
 'appropriately': 77,
 'becoming': 348,
 'food': 338,
 'actor': 6875,
 'vigorously': 9,
 'physical': 307,
 'dodging': 14,
 'beast': 205,
 'running': 992,
 'bound': 200,
 'leap': 90,
 'dangling': 19,
 'wall': 500,
 'ridiculous': 964,
 'final': 1336,
 'small': 1647,
 'realistic': 757,
 'gory': 234,
 'violent': 523,
 'attack': 607,
 'following': 565,
 'james': 1069,
 'r': 469,
 'hickox': 7,
 'vanessa': 67,
 'angel': 391,
 'david': 1025,
 'keith': 88,
 'john': 2222,
 'rhys': 34,
 'davy': 140,
 'much': 9765,
 'better': 5739,
 'bc': 18,
 'roland': 26,
 'emmerich': 4,
 'steven': 241,
 'strait': 20,
 'cliff': 127,
 'curtis': 143,
 'camilla': 12,
 'belle': 50,
 'motion': 501,
 'picture': 1937,
 'filled': 551,
 'bloody': 302,
 'badly': 662,
 'directed': 1204,
 'george': 929,
 'miller': 170,
 'originality': 171,
 'take': 5699,
 'many': 6675,
 'element': 1175,
 'previous': 630,
 'australian': 223,
 'television': 909,
 'tidal': 6,
 'wave': 266,
 'journey': 457,
 'earth': 929,
 'occasionally': 256,
 'man': 6019,
 'snowy': 37,
 'river': 344,
 'zeus': 6,
 'roxanne': 6,
 'robinson': 102,
 'crusoe': 3,
 'rating': 1094,
 'average': 723,
 'barrel': 85,
 'assumed': 82,
 'praised': 72,
 'greatest': 745,
 'filmed': 763,
 'opera': 429,
 'read': 2057,
 'somewhere': 483,
 'care': 1613,
 'wagner': 77,
 'anything': 2949,
 'except': 1129,
 'desire': 382,
 'cultured': 15,
 'representation': 80,
 'swan': 17,
 'song': 1916,
 'strike': 266,
 'unmitigated': 9,
 'disaster': 356,
 'leaden': 20,
 'reading': 703,
 'score': 1121,
 'matched': 89,
 'tricksy': 2,
 'lugubrious': 5,
 'realisation': 13,
 'text': 172,
 'questionable': 91,
 'idea': 2638,
 'matter': 1351,
 'play': 4451,
 'especially': 2535,
 'shakespeare': 297,
 'allowed': 325,
 'anywhere': 304,
 'near': 824,
 'theatre': 359,
 'studio': 698,
 'syberberg': 22,
 'fashionably': 3,
 'without': 3267,
 'smallest': 31,
 'justification': 44,
 'decided': 705,
 'parsifal': 26,
 'bisexual': 16,
 'integration': 10,
 'title': 1669,
 'stage': 785,
 'transmutes': 1,
 'kind': 2974,
 'beatnik': 8,
 'babe': 144,
 'continues': 261,
 'sing': 270,
 'tenor': 14,
 'singer': 353,
 'double': 419,
 'dose': 75,
 'armin': 9,
 'jordan': 67,
 'conductor': 48,
 'seen': 6679,
 'face': 1990,
 'heard': 1111,
 'voice': 1374,
 'amfortas': 6,
 'appears': 841,
 'monstrously': 6,
 'exposure': 88,
 'batonzilla': 1,
 'ate': 33,
 'monsalvat': 1,
 'playing': 1633,
 'friday': 201,
 'way': 8830,
 'transcendant': 2,
 'loveliness': 1,
 'represented': 99,
 'scattering': 2,
 'shopworn': 4,
 'flaccid': 12,
 'crocus': 1,
 'stuck': 350,
 'ill': 300,
 'laid': 160,
 'turf': 14,
 'expedient': 5,
 'baffle': 16,
 'sometimes': 1218,
 'piece': 1960,
 'imperfection': 13,
 'splice': 10,
 'gurnemanz': 6,
 'mountain': 306,
 'pasture': 12,
 'lush': 73,
 'provided': 207,
 'julie': 174,
 'andrew': 298,
 'sound': 1965,
 'hard': 2668,
 'endure': 99,
 'trumpet': 37,
 'particular': 734,
 'possessing': 20,
 'aural': 13,
 'glare': 7,
 'add': 1147,
 'sort': 1662,
 'fatigue': 16,
 'impatience': 4,
 'uninspired': 123,
 'conducting': 17,
 'paralytic': 1,
 'unfolding': 48,
 'ritual': 76,
 'someone': 2363,
 'review': 1566,
 'mentioned': 564,
 'bayreuth': 3,
 'recording': 101,
 'knappertsbusch': 2,
 'tempo': 24,
 'often': 1601,
 'altogether': 112,
 'lack': 1423,
 'sense': 2325,
 'pulse': 34,
 'ebb': 7,
 'flow': 205,
 'half': 2100,
 'century': 580,
 'orchestral': 31,
 'set': 3307,
 'modern': 931,
 'pressing': 26,
 'still': 5655,
 'superior': 344,
 'superbly': 126,
 'trashy': 99,
 'wondrously': 2,
 'unpretentious': 25,
 'exploitation': 234,
 'hooray': 19,
 'credit': 1204,
 'opening': 982,
 'somewhat': 965,
 'false': 193,
 'impression': 444,
 'dealing': 284,
 'serious': 989,
 'harrowing': 46,
 'drama': 1552,
 'need': 2648,
 'fear': 664,
 'barely': 483,
 'ten': 851,
 'later': 2200,
 'neck': 164,
 'nonsensical': 82,
 'chainsaw': 78,
 'battle': 750,
 'rough': 187,
 'fist': 96,
 'lurid': 39,
 'dialog': 911,
 'gratuitous': 237,
 'nudity': 596,
 'bo': 156,
 'ingrid': 62,
 'two': 6908,
 'orphaned': 11,
 'sibling': 100,
 'unusually': 52,
 'close': 1323,
 'even': 12646,
 'slightly': 541,
 'perverted': 45,
 'relationship': 1327,
 'imagine': 737,
 'playfully': 12,
 'ripping': 64,
 'towel': 30,
 'cover': 661,
 'sister': 1025,
 'naked': 437,
 'body': 1190,
 'stare': 102,
 'unshaven': 4,
 'genitals': 24,
 'several': 1420,
 'judging': 102,
 'dubbed': 224,
 'laughter': 247,
 'sick': 487,
 'dude': 207,
 'fled': 21,
 'russia': 79,
 'parent': 881,
 'nasty': 342,
 'soldier': 770,
 'brutally': 90,
 'slaughtered': 37,
 'mommy': 27,
 'daddy': 109,
 'friendly': 193,
 'smuggler': 12,
 'took': 1100,
 'custody': 35,
 'raised': 170,
 'trained': 97,
 'expert': 218,
 'plot': 6870,
 'lift': 106,
 'facing': 96,
 'ultimate': 248,
 'quest': 187,
 'mythical': 39,
 'incredibly': 626,
 'valuable': 97,
 'white': 1546,
 'fire': 676,
 'diamond': 153,
 'coincidentally': 29,
 'mine': 314,
 'life': 8032,
 'little': 6435,
 'narrative': 448,
 'structure': 216,
 'sure': 2683,
 'fun': 2694,
 'watch': 7095,
 'time': 15959,
 'clue': 347,
 'beating': 154,
 'cause': 700,
 'bet': 274,
 'understood': 179,
 'less': 2002,
 'whatever': 732,
 'violence': 1091,
 'magnificently': 29,
 'grotesque': 79,
 'single': 939,
 'twist': 1043,
 'pleasingly': 9,
 'retarded': 161,
 'script': 3173,
 'bonkers': 16,
 'repair': 35,
 'suddenly': 538,
 'reveal': 189,
 'reason': 2919,
 'replacement': 52,
 'fred': 303,
 'williamson': 22,
 'enters': 131,
 'big': 3477,
 'cigar': 32,
 'mouth': 386,
 'sleazy': 164,
 'black': 2108,
 'finger': 174,
 'local': 947,
 'prostitute': 151,
 'principal': 162,
 'opponent': 66,
 'italian': 562,
 'chick': 322,
 'breast': 179,
 'hideous': 103,
 'accent': 688,
 'preposterous': 75,
 'catchy': 91,
 'theme': 1239,
 'least': 3112,
 'dozen': 299,
 'throughout': 1360,
 'obligatory': 70,
 'falling': 383,
 'love': 6858,
 'montage': 136,
 'load': 216,
 'attraction': 159,
 'god': 1271,
 'brilliant': 1195,
 'experience': 1259,
 'original': 3427,
 'french': 790,
 'translates': 17,
 'survive': 260,
 'uniquely': 31,
 'appropriate': 221,
 'rest': 1836,
 'none': 1032,
 'dont': 74,
 'got': 3583,
 'pretty': 3664,
 'action': 3665,
 'change': 1345,
 'location': 600,
 'harry': 461,
 'hurt': 481,
 'offensive': 212,
 'eastwood': 138,
 'form': 865,
 'dirty': 334,
 'liked': 1516,
 'pat': 145,
 'hingle': 10,
 'town': 1318,
 'cop': 921,
 'pool': 158,
 'could': 7922,
 'short': 2013,
 'cheesy': 634,
 'acting': 6491,
 'looked': 1010,
 'past': 1275,
 'background': 720,
 'around': 3616,
 'evil': 1463,
 'druid': 12,
 'witch': 414,
 'linked': 49,
 'woman': 4616,
 'migraine': 11,
 'drag': 341,
 'clearly': 899,
 'explains': 193,
 'keep': 2243,
 'plodding': 50,
 'christopher': 415,
 'walken': 142,
 'completely': 1889,
 'senseless': 101,
 'potential': 616,
 'tv': 2790,
 'avoid': 775,
 'video': 1866,
 'friend': 3230,
 'house': 2289,
 'glad': 450,
 'waste': 1509,
 'money': 2368,
 'buying': 184,
 'capricorn': 2,
 'clip': 245,
 'rocket': 141,
 'blow': 324,
 'ups': 266,
 'related': 202,
 'manned': 6,
 'flight': 188,
 'sibrel': 17,
 'smoking': 134,
 'gun': 846,
 'astronaut': 70,
 'preparing': 63,
 'broadcast': 127,
 'edits': 32,
 'instead': 2190,
 'letting': 146,
 'u': 4281,
 'listen': 331,
 'crew': 582,
 'curiously': 49,
 'end': 6632,
 'showing': 786,
 'zapruder': 3,
 'claim': 427,
 'radiation': 45,
 'shielding': 1,
 'photography': 406,
 'lead': 2060,
 'believe': 2505,
 'ignorant': 96,
 'ax': 33,
 'grind': 34,
 'nasa': 26,
 'american': 2593,
 'general': 784,
 'science': 556,
 'bought': 458,
 'grossly': 38,
 'overpriced': 4,
 'despite': 1364,
 'featuring': 277,
 'name': 1995,
 'adam': 400,
 'sandler': 174,
 'billy': 377,
 'bob': 271,
 'thornton': 26,
 'burt': 167,
 'young': 3663,
 'funny': 4288,
 'taking': 955,
 'chisel': 2,
 'hammering': 9,
 'straight': 868,
 'earhole': 1,
 'us': 544,
 'tired': 380,
 'comedic': 315,
 'technique': 286,
 'consistently': 104,
 'breaking': 231,
 'fourth': 178,
 'talk': 1062,
 'audience': 2675,
 'seemingly': 347,
 'pointless': 504,
 'hot': 688,
 'waiter': 32,
 'ship': 426,
 'successful': 524,
 'comedian': 236,
 'order': 1060,
 'become': 1544,
 'resident': 145,
 'shamelessly': 35,
 'named': 799,
 'dickie': 8,
 'due': 918,
 'unfathomable': 20,
 'success': 613,
 'opposite': 282,
 'gender': 102,
 'presumed': 32,
 'lost': 1554,
 'sea': 291,
 'shecker': 1,
 'break': 870,
 'rather': 2733,
 'locked': 167,
 'bathroom': 117,
 'presumably': 127,
 'perhaps': 1681,
 'vomited': 8,
 'worst': 2731,
 'reference': 415,
 'mad': 499,
 'max': 215,
 'ii': 366,
 'wild': 441,
 'ladybug': 8,
 'clear': 791,
 'tribute': 144,
 'peter': 853,
 'lorre': 37,
 'masterpiece': 697,
 'future': 909,
 'happens': 1080,
 'army': 474,
 'wetback': 1,
 'towelheads': 1,
 'godless': 5,
 'eastern': 83,
 'european': 340,
 'commie': 32,
 'gather': 98,
 'force': 786,
 'south': 472,
 'border': 178,
 'gary': 272,
 'busey': 57,
 'kick': 397,
 'butt': 147,
 'laughable': 422,
 'example': 1554,
 'reagan': 46,
 'era': 635,
 'cultural': 184,
 'fallout': 11,
 'bulletproof': 9,
 'decent': 1157,
 'supporting': 899,
 'cast': 3894,
 'headed': 169,
 'l': 432,
 'q': 116,
 'jones': 410,
 'thalmus': 4,
 'rasulala': 4,
 'although': 2537,
 'generally': 468,
 'remake': 660,
 'believing': 137,
 'exception': 471,
 'actually': 4237,
 'far': 2978,
 'comment': 1432,
 'opinion': 1048,
 'purely': 169,
 'comparison': 320,
 'written': 1616,
 'question': 1164,
 'capote': 64,
 'word': 1811,
 'anthony': 263,
 'edward': 233,
 'eric': 265,
 'superb': 671,
 'case': 1696,
 'always': 3239,
 'wondered': 126,
 'number': 1409,
 'famous': 771,
 'brother': 1670,
 'certainty': 23,
 'top': 1911,
 'profession': 71,
 'recommend': 1667,
 'dvd': 2411,
 'shelf': 140,
 'harvey': 107,
 'light': 1157,
 'candle': 72,
 'anchored': 9,
 'spall': 20,
 'predict': 69,
 'titular': 44,
 'morose': 17,
 'tight': 182,
 'teacher': 391,
 'catharsis': 16,
 'based': 1430,
 'deep': 654,
 'emotion': 785,
 'unveiled': 7,
 'surprising': 302,
 'range': 263,
 'conveyed': 58,
 'moving': 854,
 'portray': 264,
 'mike': 288,
 'leigh': 76,
 'repertory': 4,
 'expected': 704,
 'school': 1725,
 'bus': 203,
 'trip': 520,
 'used': 1879,
 'comic': 1034,
 'purpose': 523,
 'simpson': 146,
 'central': 411,
 'situation': 1155,
 'visit': 351,
 'salisbury': 3,
 'cathedral': 17,
 'rhidian': 2,
 'brook': 184,
 'contained': 113,
 'structured': 40,
 'dramatic': 667,
 'almost': 3139,
 'formally': 3,
 'divided': 47,
 'act': 1645,
 'introduced': 313,
 'urban': 189,
 'british': 898,
 'racially': 14,
 'religiously': 13,
 'diverse': 54,
 'uniform': 110,
 'tell': 2598,
 'private': 280,
 'public': 566,
 'rapping': 16,
 'asian': 260,
 'muslim': 136,
 'bully': 108,
 'mean': 2444,
 'naturally': 267,
 'individually': 21,
 'recognized': 113,
 'shameless': 45,
 'exuberant': 23,
 'representing': 39,
 'usual': 965,
 'junior': 92,
 'social': 584,
 'pressure': 109,
 'celia': 14,
 'imrie': 4,
 'warmth': 86,
 'supervisor': 13,
 'role': 4300,
 'martinet': 3,
 'transformative': 5,
 'crisis': 164,
 ...}

In [16]:
sorted_freq_words = dict(sorted(freq_list.items(), key = lambda item:item[1], reverse = True))
sorted_freq_words

{'movie': 51694,
 'film': 47034,
 'one': 27741,
 'like': 20740,
 'time': 15959,
 'good': 15197,
 'character': 14177,
 'story': 13165,
 'even': 12646,
 'get': 12514,
 'would': 12436,
 'make': 12225,
 'see': 12012,
 'really': 11736,
 'well': 10783,
 'scene': 10585,
 'much': 9765,
 'people': 9385,
 'bad': 9302,
 'also': 9156,
 'great': 9088,
 'first': 9062,
 'way': 8830,
 'show': 8603,
 'made': 8362,
 'thing': 8214,
 'life': 8032,
 'could': 7922,
 'think': 7733,
 'go': 7600,
 'watch': 7095,
 'know': 7067,
 'two': 6908,
 'year': 6878,
 'actor': 6875,
 'plot': 6870,
 'love': 6858,
 'seen': 6679,
 'many': 6675,
 'end': 6632,
 'look': 6558,
 'say': 6505,
 'acting': 6491,
 'never': 6484,
 'little': 6435,
 'best': 6420,
 'man': 6019,
 'ever': 5995,
 'better': 5739,
 'take': 5699,
 'come': 5673,
 'still': 5655,
 'work': 5650,
 'part': 5233,
 'director': 5119,
 'find': 5079,
 'something': 5077,
 'back': 5045,
 'want': 4990,
 'give': 4952,
 'lot': 4778,
 'real': 4738,
 'performance': 4717,
 'woman': 4616,
 'watching': 4605,
 'old': 4579,
 'though': 4566,
 'play': 4451,
 'guy': 4339,
 'another': 4325,
 'new': 4310,
 'role': 4300,
 'nothing': 4292,
 'funny': 4288,
 'u': 4281,
 'actually': 4237,
 'going': 4146,
 'girl': 4064,
 'point': 4039,
 'day': 4014,
 'world': 3978,
 'every': 3978,
 'cast': 3894,
 'star': 3782,
 'feel': 3760,
 'fact': 3747,
 'minute': 3741,
 'quite': 3738,
 'horror': 3716,
 'comedy': 3684,
 'action': 3665,
 'pretty': 3664,
 'young': 3663,
 'thought': 3656,
 'seems': 3618,
 'around': 3616,
 'got': 3583,
 'however': 3537,
 'right': 3497,
 'big': 3477,
 'enough': 3452,
 'long': 3449,
 'family': 3440,
 'original': 3427,
 'line': 3422,
 'series': 3416,
 'may': 3392,
 'bit': 3349,
 'fan': 3332,
 'set': 3307,
 'without': 3267,
 'must': 3250,
 'always': 3239,
 'friend': 3230,
 'script': 3173,
 'saw': 3171,
 'almost': 3139,
 'interesting': 3128,
 'least': 3112,
 'try': 3109,
 'done': 3096,
 'whole': 3079,
 'music': 3061,
 'kid': 3043,
 'shot': 2998,
 'last': 2993,
 'making': 2978,
 'far': 2978,
 'kind': 2974,
 'anything': 2949,
 'book': 2926,
 'start': 2920,
 'reason': 2919,
 'might': 2919,
 'since': 2906,
 'probably': 2841,
 'effect': 2837,
 'child': 2833,
 'place': 2822,
 'tv': 2790,
 'moment': 2775,
 'away': 2775,
 'put': 2760,
 'yet': 2753,
 'rather': 2733,
 'worst': 2731,
 'fun': 2694,
 'sure': 2683,
 'let': 2675,
 'audience': 2675,
 'hard': 2668,
 'need': 2648,
 'idea': 2638,
 'anyone': 2630,
 'turn': 2610,
 'tell': 2598,
 'episode': 2597,
 'american': 2593,
 'played': 2588,
 'found': 2576,
 'screen': 2566,
 'although': 2537,
 'especially': 2535,
 'course': 2517,
 'believe': 2505,
 'looking': 2483,
 'trying': 2473,
 'ending': 2462,
 'job': 2459,
 'mean': 2444,
 'dvd': 2411,
 'version': 2410,
 'different': 2385,
 'war': 2383,
 'money': 2368,
 'someone': 2363,
 'maybe': 2340,
 'problem': 2337,
 'true': 2333,
 'sense': 2325,
 'everything': 2321,
 'second': 2310,
 'three': 2297,
 'night': 2293,
 'house': 2289,
 'worth': 2279,
 'main': 2265,
 'help': 2255,
 'wife': 2245,
 'keep': 2243,
 'together': 2243,
 'watched': 2236,
 'everyone': 2222,
 'john': 2222,
 'later': 2200,
 'father': 2199,
 'said': 2196,
 'instead': 2190,
 'mind': 2180,
 'boy': 2178,
 'beautiful': 2177,
 'seem': 2175,
 'high': 2174,
 'hour': 2171,
 'special': 2135,
 'left': 2125,
 'death': 2113,
 'black': 2108,
 'half': 2100,
 'seeing': 2099,
 'excellent': 2070,
 'eye': 2065,
 'classic': 2061,
 'lead': 2060,
 'read': 2057,
 'viewer': 2047,
 'laugh': 2032,
 'short': 2013,
 'nice': 2012,
 'less': 2002,
 'else': 1998,
 'name': 1995,
 'face': 1990,
 'production': 1973,
 'sound': 1965,
 'simply': 1965,
 'piece': 1960,
 'home': 1939,
 'picture': 1937,
 'song': 1916,
 'human': 1915,
 'men': 1915,
 'hollywood': 1911,
 'top': 1911,
 'poor': 1897,
 'budget': 1894,
 'completely': 1889,
 'hand': 1889,
 'camera': 1888,
 'dead': 1881,
 'used': 1879,
 'either': 1866,
 'video': 1866,
 'given': 1849,
 'rest': 1836,
 'wrong': 1833,
 'head': 1832,
 'low': 1817,
 'writer': 1814,
 'couple': 1812,
 'enjoy': 1812,
 'word': 1811,
 'boring': 1809,
 'use': 1803,
 'full': 1780,
 'along': 1776,
 'kill': 1764,
 'truly': 1743,
 'run': 1731,
 'school': 1725,
 'awful': 1724,
 'hope': 1720,
 'next': 1716,
 'style': 1715,
 'sex': 1712,
 'mr': 1708,
 'remember': 1702,
 'stupid': 1701,
 'killer': 1700,
 'case': 1696,
 'person': 1686,
 'perhaps': 1681,
 'came': 1673,
 'brother': 1670,
 'title': 1669,
 'recommend': 1667,
 'sort': 1662,
 'wonderful': 1656,
 'dialogue': 1652,
 'small': 1647,
 'act': 1645,
 'understand': 1643,
 'terrible': 1638,
 'playing': 1633,
 'attempt': 1633,
 'getting': 1627,
 'fall': 1621,
 'game': 1621,
 'written': 1616,
 'flick': 1615,
 'care': 1613,
 'early': 1605,
 'sequence': 1603,
 'art': 1603,
 'often': 1601,
 'joke': 1600,
 'perfect': 1600,
 'others': 1595,
 'mother': 1593,
 'actress': 1588,
 'definitely': 1580,
 'review': 1566,
 'lost': 1554,
 'example': 1554,
 'cinema': 1553,
 'drama': 1552,
 'live': 1552,
 'white': 1546,
 'become': 1544,
 'feeling': 1540,
 'finally': 1536,
 'yes': 1535,
 'felt': 1528,
 'liked': 1516,
 'supposed': 1516,
 'waste': 1509,
 'quality': 1509,
 'son': 1506,
 'car': 1504,
 'absolutely': 1485,
 'begin': 1473,
 'worse': 1468,
 'evil': 1463,
 'heart': 1463,
 'went': 1463,
 'certainly': 1462,
 'entire': 1460,
 'direction': 1453,
 'oh': 1450,
 'entertaining': 1442,
 'overall': 1438,
 'feature': 1434,
 'side': 1434,
 'fight': 1433,
 'called': 1433,
 'comment': 1432,
 'based': 1430,
 'murder': 1430,
 'loved': 1428,
 'beginning': 1426,
 'lack': 1423,
 'several': 1420,
 'favorite': 1419,
 'number': 1409,
 'hero': 1388,
 'already': 1381,
 'dark': 1380,
 'becomes': 1380,
 'voice': 1374,
 'type': 1371,
 'michael': 1370,
 'age': 1370,
 'genre': 1367,
 'despite': 1364,
 'seemed': 1363,
 'throughout': 1360,
 'hit': 1360,
 'wanted': 1352,
 'unfortunately': 1352,
 'matter': 1351,
 'change': 1345,
 'meet': 1345,
 'b': 1339,
 'history': 1338,
 'final': 1336,
 'writing': 1332,
 'relationship': 1327,
 'fine': 1326,
 'close': 1323,
 'amazing': 1320,
 'town': 1318,
 'humor': 1317,
 'guess': 1315,
 'daughter': 1312,
 'cut': 1309,
 'totally': 1307,
 'event': 1283,
 'city': 1283,
 'today': 1282,
 'behind': 1280,
 'past': 1275,
 'god': 1271,
 'power': 1265,
 'experience': 1259,
 'able': 1259,
 'zombie': 1258,
 'move': 1257,
 'enjoyed': 1245,
 'stop': 1242,
 'theme': 1239,
 'soon': 1222,
 'sometimes': 1218,
 'gave': 1216,
 'stand': 1213,
 'etc': 1212,
 'late': 1211,
 'directed': 1204,
 'credit': 1204,
 'self': 1202,
 'horrible': 1201,
 'talent': 1201,
 'chance': 1200,
 'level': 1198,
 'brilliant': 1195,
 'body': 1190,
 'blood': 1186,
 'call': 1183,
 'stuff': 1181,
 'thinking': 1179,
 'expect': 1176,
 'element': 1175,
 'musical': 1167,
 'save': 1166,
 'question': 1164,
 'obviously': 1163,
 'wonder': 1163,
 'decent': 1157,
 'light': 1157,
 'situation': 1155,
 'add': 1147,
 'highly': 1147,
 'view': 1145,
 'lady': 1144,
 'group': 1142,
 'slow': 1131,
 'except': 1129,
 'novel': 1126,
 'score': 1121,
 'anyway': 1117,
 'interest': 1115,
 'career': 1114,
 'heard': 1111,
 'wish': 1111,
 'killed': 1111,
 'leave': 1107,
 'husband': 1105,
 'took': 1100,
 'dream': 1099,
 'police': 1098,
 'strong': 1096,
 'cannot': 1096,
 'rating': 1094,
 'robert': 1093,
 'violence': 1091,
 'country': 1086,
 'happens': 1080,
 'known': 1080,
 'particularly': 1079,
 'happened': 1076,
 'involved': 1076,
 'documentary': 1074,
 'extremely': 1069,
 'james': 1069,
 'obvious': 1066,
 'coming': 1065,
 'living': 1063,
 'told': 1063,
 'talk': 1062,
 'alone': 1061,
 'order': 1060,
 'theater': 1057,
 'including': 1052,
 'reality': 1050,
 'crap': 1049,
 'opinion': 1048,
 'effort': 1046,
 'thriller': 1046,
 'please': 1045,
 'room': 1044,
 'twist': 1043,
 'happen': 1043,
 'sequel': 1042,
 'gore': 1040,
 'king': 1037,
 'complete': 1035,
 'comic': 1034,
 'ago': 1033,
 'none': 1032,
 'hell': 1032,
 'david': 1025,
 'sister': 1025,
 'simple': 1023,
 'female': 1022,
 'ok': 1017,
 'rock': 1014,
 'looked': 1010,
 'season': 1010,
 'oscar': 1007,
 'seriously': 1002,
 'miss': 1001,
 'possible': 999,
 'class': 999,
 'annoying': 998,
 'sad': 996,
 'exactly': 995,
 'shown': 994,
 'running': 992,
 'value': 991,
 'serious': 989,
 'scary': 988,
 'released': 986,
 'taken': 986,
 'whose': 986,
 'english': 986,
 'cinematography': 983,
 'opening': 982,
 'usually': 981,
 'spoiler': 976,
 'deal': 975,
 'hilarious': 973,
 'cool': 971,
 'across': 971,
 'stay': 969,
 'street': 968,
 'somewhat': 965,
 'usual': 965,
 'happy': 965,
 'ridiculous': 964,
 'started': 963,
 'message': 960,
 'middle': 958,
 'tale': 956,
 'taking': 955,
 'mystery': 955,
 'talking': 954,
 'saying': 952,
 'figure': 949,
 'local': 947,
 'major': 946,
 'huge': 944,
 'mostly': 941,
 'single': 939,
 'five': 936,
 'jack': 933,
 'monster': 932,
 'important': 931,
 'modern': 931,
 'return': 931,
 'attention': 929,
 'george': 929,
 'earth': 929,
 'producer': 927,
 'strange': 926,
 'turned': 925,
 'open': 923,
 'cop': 921,
 'due': 918,
 'surprise': 918,
 'apparently': 917,
 'disappointed': 917,
 'four': 915,
 'dialog': 911,
 'television': 909,
 'future': 909,
 'result': 906,
 'basically': 906,
 'filmmaker': 900,
 'clearly': 899,
 'supporting': 899,
 'british': 898,
 'paul': 898,
 'non': 898,
 'knew': 897,
 'fast': 897,
 'mention': 896,
 'crime': 896,
 'hate': 893,
 'easily': 892,
 'cheap': 892,
 'silly': 888,
 'entertainment': 887,
 'dog': 887,
 'adult': 886,
 'release': 883,
 'team': 883,
 'parent': 881,
 'member': 879,
 'villain': 878,
 'break': 870,
 'bring': 869,
 'straight': 868,
 'state': 868,
 'beyond': 866,
 'form': 865,
 'animation': 864,
 'romantic': 863,
 'upon': 859,
 'whether': 856,
 'predictable': 854,
 'moving': 854,
 'peter': 853,
 'aspect': 852,
 'similar': 852,
 'ten': 851,
 'image': 851,
 'dance': 847,
 'richard': 847,
 'gun': 846,
 'hold': 845,
 'enjoyable': 842,
 'appears': 841,
 'note': 841,
 'giving': 840,
 'clich': 840,
 'doubt': 839,
 'viewing': 838,
 'within': 832,
 'red': 831,
 'killing': 826,
 'e': 825,
 'near': 824,
 'buy': 823,
 'present': 823,
 'storyline': 822,
 'working': 817,
 'bunch': 817,
 'lee': 817,
 'subject': 816,
 'dull': 816,
 'period': 815,
 'nearly': 815,
 'york': 811,
 'setting': 809,
 'standard': 803,
 'easy': 802,
 'using': 801,
 'surprised': 801,
 'named': 799,
 'fantastic': 798,
 'die': 794,
 'actual': 793,
 'victim': 793,
 'de': 792,
 'check': 792,
 'clear': 791,
 'french': 790,
 'material': 789,
 'showing': 786,
 'force': 786,
 'space': 786,
 'tom': 785,
 'stage': 785,
 'emotion': 785,
 'follow': 785,
 'general': 784,
 'among': 783,
 'typical': 778,
 'soundtrack': 778,
 'third': 776,
 'avoid': 775,
 'editing': 774,
 'tried': 773,
 'famous': 771,
 'sorry': 771,
 'soldier': 770,
 'baby': 769,
 'mark': 765,
 'certain': 764,
 'western': 764,
 'filmed': 763,
 'weak': 761,
 'realistic': 757,
 'somehow': 757,
 'disney': 756,
 'detail': 755,
 'gone': 754,
 'animal': 752,
 'wait': 752,
 'student': 752,
 'truth': 752,
 'battle': 750,
 'kept': 750,
 'cartoon': 750,
 'romance': 747,
 'premise': 746,
 'greatest': 745,
 'th': 745,
 'rent': 742,
 'lame': 742,
 'atmosphere': 741,
 'suspense': 739,
 'imagine': 737,
 'america': 737,
 'brought': 737,
 'screenplay': 735,
 'particular': 734,
 'hear': 733,
 'whatever': 732,
 'drug': 728,
 'male': 727,
 'fantasy': 725,
 'secret': 724,
 'walk': 724,
 'offer': 724,
 'nature': 723,
 'average': 723,
 'indeed': 722,
 'background': 720,
 'eventually': 720,
 'learn': 720,
 'forget': 716,
 'pay': 716,
 'adventure': 714,
 'japanese': 714,
 'poorly': 713,
 'believable': 711,
 'sexual': 710,
 'sit': 709,
 'possibly': 709,
 'society': 707,
 'okay': 706,
 'decided': 705,
 'issue': 705,
 'free': 705,
 'rate': 704,
 'expected': 704,
 'fit': 704,
 'leaf': 704,
 'reading': 703,
 'imdb': 702,
 'dr': 702,
 'escape': 701,
 'cause': 700,
 'choice': 699,
 'studio': 698,
 'masterpiece': 697,
 'became': 697,
 'difficult': 695,
 'doctor': 692,
 'focus': 691,
 'joe': 690,
 'match': 689,
 'accent': 688,
 'hot': 688,
 'lover': 688,
 'girlfriend': 684,
 'needed': 683,
 'beauty': 679,
 'development': 679,
 'touch': 678,
 'fire': 676,
 'unless': 675,
 'shame': 675,
 'box': 672,
 'forward': 672,
 'superb': 671,
 'bill': 671,
 'wood': 671,
 'otherwise': 670,
 'write': 670,
 'crazy': 670,
 'vampire': 668,
 'dramatic': 667,
 'memorable': 666,
 'copy': 665,
 'ghost': 665,
 'fear': 664,
 'award': 664,
 'weird': 664,
 'badly': 662,
 'week': 662,
 'earlier': 662,
 'cover': 661,
 'fi': 661,
 'mess': 661,
 'remake': 660,
 'forced': 660,
 'sci': 658,
 'acted': 658,
 'emotional': 657,
 'maker': 657,
 'cat': 657,
 'jane': 657,
 'footage': 656,
 'older': 656,
 'water': 655,
 'win': 655,
 'deep': 654,
 'realize': 654,
 'air': 652,
 'plus': 651,
 'spirit': 650,
 'interested': 650,
 'cry': 649,
 'ask': 648,
 'gay': 645,
 'directing': 644,
 'c': 643,
 'costume': 641,
 'quickly': 639,
 'business': 639,
 'creepy': 638,
 'towards': 637,
 'perfectly': 637,
 'party': 637,
 'era': 635,
 'co': 635,
 'worked': 635,
 'cheesy': 634,
 'unique': 634,
 'total': 632,
 'plenty': 632,
 'previous': 630,
 'brings': 630,
 'personal': 630,
 'christmas': 629,
 'incredibly': 626,
 'mistake': 626,
 'casting': 626,
 'plan': 625,
 'project': 623,
 'list': 623,
 'apart': 623,
 'leading': 622,
 'band': 622,
 'pick': 621,
 'admit': 621,
 'powerful': 620,
 'front': 620,
 'appear': 619,
 'ben': 617,
 'telling': 617,
 'potential': 616,
 'meant': 614,
 'la': 614,
 'hardly': 613,
 'success': 613,
 'create': 612,
 'rich': 610,
 'dumb': 609,
 'political': 608,
 'attack': 607,
 'fighting': 607,
 'inside': 607,
 'german': 607,
 'law': 606,
 'trouble': 606,
 'fails': 606,
 'drive': 603,
 'various': 603,
 'shoot': 602,
 'portrayed': 601,
 'color': 601,
 'location': 600,
 'term': 600,
 'outside': 597,
 'nudity': 596,
 'company': 596,
 'william': 596,
 'sweet': 595,
 'missing': 594,
 'deserves': 591,
 'married': 590,
 'appearance': 590,
 'flat': 589,
 'office': 588,
 'expecting': 588,
 'store': 587,
 'fairly': 587,
 'scott': 587,
 'talented': 586,
 'player': 586,
 'stick': 586,
 'concept': 586,
 'memory': 585,
 'amount': 585,
 'unlike': 585,
 'social': 584,
 'brain': 583,
 'manages': 583,
 'odd': 582,
 'crew': 582,
 'plain': 582,
 'chase': 581,
 'cute': 581,
 'century': 580,
 'recently': 579,
 'portrayal': 578,
 'island': 575,
 'sadly': 575,
 'tension': 574,
 'wrote': 573,
 'agree': 572,
 'alien': 572,
 'cold': 571,
 'depth': 570,
 'throw': 569,
 'mary': 567,
 'public': 566,
 'language': 566,
 'following': 565,
 'missed': 565,
 'mentioned': 564,
 'incredible': 563,
 'italian': 562,
 'ability': 562,
 'pure': 562,
 'pace': 561,
 'wasted': 560,
 'master': 560,
 'door': 557,
 'control': 557,
 'large': 556,
 'science': 556,
 'ended': 556,
 'caught': 555,
 'revenge': 555,
 'produced': 555,
 'creature': 554,
 'catch': 553,
 'v': 552,
 'respect': 552,
 'filled': 551,
 'culture': 550,
 'popular': 550,
 'waiting': 549,
 'positive': 548,
 'basic': 547,
 'million': 546,
 'tone': 546,
 'decides': 546,
 'considering': 545,
 'us': 544,
 'extra': 543,
 'soul': 542,
 'created': 542,
 'slightly': 541,
 'slasher': 539,
 'familiar': 539,
 'convincing': 538,
 'suddenly': 538,
 'compared': 538,
 'f': 538,
 'neither': 537,
 'teen': 537,
 'answer': 537,
 'spent': 536,
 'planet': 534,
 'computer': 534,
 'conclusion': 534,
 'hole': 534,
 'intelligent': 534,
 'adaptation': 533,
 'clever': 533,
 'entirely': 532,
 'blue': 531,
 'bored': 530,
 'dancing': 529,
 'laughing': 528,
 'channel': 528,
 'indian': 527,
 'pull': 526,
 'detective': 526,
 'successful': 524,
 'violent': 523,
 'purpose': 523,
 'visual': 523,
 'critic': 522,
 'spot': 522,
 'speak': 522,
 'tony': 522,
 'ultimately': 521,
 'trip': 520,
 'singing': 520,
 'hair': 519,
 'step': 519,
 'animated': 516,
 'exciting': 515,
 'biggest': 515,
 'taste': 515,
 'trash': 514,
 'consider': 513,
 'artist': 513,
 'died': 512,
 'effective': 512,
 'shooting': 511,
 'dad': 511,
 'recent': 510,
 'amusing': 509,
 'meaning': 509,
 'former': 509,
 'college': 509,
 'common': 509,
 'belief': 508,
 'spend': 508,
 'reviewer': 507,
 'rated': 507,
 'date': 507,
 'van': 507,
 'appreciate': 507,
 'appeal': 506,
 'pointless': 504,
 'track': 504,
 'solid': 504,
 'prison': 504,
 'post': 503,
 'younger': 503,
 'capture': 503,
 'heavy': 502,
 'cult': 502,
 ...}

In [17]:
from collections import Counter
cnt = Counter(" ".join(train['clean_review'].tolist()).split())

In [18]:
cnt

Counter({'movie': 51694,
         'film': 47034,
         'one': 27741,
         'like': 20740,
         'time': 15959,
         'good': 15197,
         'character': 14177,
         'story': 13165,
         'even': 12646,
         'get': 12514,
         'would': 12436,
         'make': 12225,
         'see': 12012,
         'really': 11736,
         'well': 10783,
         'scene': 10585,
         'much': 9765,
         'people': 9385,
         'bad': 9302,
         'also': 9156,
         'great': 9088,
         'first': 9062,
         'way': 8830,
         'show': 8603,
         'made': 8362,
         'thing': 8214,
         'life': 8032,
         'could': 7922,
         'think': 7733,
         'go': 7600,
         'watch': 7095,
         'know': 7067,
         'two': 6908,
         'year': 6878,
         'actor': 6875,
         'plot': 6870,
         'love': 6858,
         'seen': 6679,
         'many': 6675,
         'end': 6632,
         'look': 6558,
         'say': 6505,
         'acting': 6491,
         'never': 6484,
         'little': 6435,
         'best': 6420,
         'man': 6019,
         'ever': 5995,
         'better': 5739,
         'take': 5699,
         'come': 5673,
         'still': 5655,
         'work': 5650,
         'part': 5233,
         'director': 5119,
         'find': 5079,
         'something': 5077,
         'back': 5045,
         'want': 4990,
         'give': 4952,
         'lot': 4778,
         'real': 4738,
         'performance': 4717,
         'woman': 4616,
         'watching': 4605,
         'old': 4579,
         'though': 4566,
         'play': 4451,
         'guy': 4339,
         'another': 4325,
         'new': 4310,
         'role': 4300,
         'nothing': 4292,
         'funny': 4288,
         'u': 4281,
         'actually': 4237,
         'going': 4146,
         'girl': 4064,
         'point': 4039,
         'day': 4014,
         'world': 3978,
         'every': 3978,
         'cast': 3894,
         'star': 3782,
         'feel': 3760,
         'fact': 3747,
         'minute': 3741,
         'quite': 3738,
         'horror': 3716,
         'comedy': 3684,
         'action': 3665,
         'pretty': 3664,
         'young': 3663,
         'thought': 3656,
         'seems': 3618,
         'around': 3616,
         'got': 3583,
         'however': 3537,
         'right': 3497,
         'big': 3477,
         'enough': 3452,
         'long': 3449,
         'family': 3440,
         'original': 3427,
         'line': 3422,
         'series': 3416,
         'may': 3392,
         'bit': 3349,
         'fan': 3332,
         'set': 3307,
         'without': 3267,
         'must': 3250,
         'always': 3239,
         'friend': 3230,
         'script': 3173,
         'saw': 3171,
         'almost': 3139,
         'interesting': 3128,
         'least': 3112,
         'try': 3109,
         'done': 3096,
         'whole': 3079,
         'music': 3061,
         'kid': 3043,
         'shot': 2998,
         'last': 2993,
         'making': 2978,
         'far': 2978,
         'kind': 2974,
         'anything': 2949,
         'book': 2926,
         'start': 2920,
         'reason': 2919,
         'might': 2919,
         'since': 2906,
         'probably': 2841,
         'effect': 2837,
         'child': 2833,
         'place': 2822,
         'tv': 2790,
         'moment': 2775,
         'away': 2775,
         'put': 2760,
         'yet': 2753,
         'rather': 2733,
         'worst': 2731,
         'fun': 2694,
         'sure': 2683,
         'let': 2675,
         'audience': 2675,
         'hard': 2668,
         'need': 2648,
         'idea': 2638,
         'anyone': 2630,
         'turn': 2610,
         'tell': 2598,
         'episode': 2597,
         'american': 2593,
         'played': 2588,
         'found': 2576,
         'screen': 2566,
         'although': 2537,
         'especially': 2535,
         'course': 2517,
         'believe': 2505,
         'looking': 2483,
         'trying': 2473,
         'ending': 2462,
         'job': 2459,
         'mean': 2444,
         'dvd': 2411,
         'version': 2410,
         'different': 2385,
         'war': 2383,
         'money': 2368,
         'someone': 2363,
         'maybe': 2340,
         'problem': 2337,
         'true': 2333,
         'sense': 2325,
         'everything': 2321,
         'second': 2310,
         'three': 2297,
         'night': 2293,
         'house': 2289,
         'worth': 2279,
         'main': 2265,
         'help': 2255,
         'wife': 2245,
         'keep': 2243,
         'together': 2243,
         'watched': 2236,
         'everyone': 2222,
         'john': 2222,
         'later': 2200,
         'father': 2199,
         'said': 2196,
         'instead': 2190,
         'mind': 2180,
         'boy': 2178,
         'beautiful': 2177,
         'seem': 2175,
         'high': 2174,
         'hour': 2171,
         'special': 2135,
         'left': 2125,
         'death': 2113,
         'black': 2108,
         'half': 2100,
         'seeing': 2099,
         'excellent': 2070,
         'eye': 2065,
         'classic': 2061,
         'lead': 2060,
         'read': 2057,
         'viewer': 2047,
         'laugh': 2032,
         'short': 2013,
         'nice': 2012,
         'less': 2002,
         'else': 1998,
         'name': 1995,
         'face': 1990,
         'production': 1973,
         'sound': 1965,
         'simply': 1965,
         'piece': 1960,
         'home': 1939,
         'picture': 1937,
         'song': 1916,
         'human': 1915,
         'men': 1915,
         'hollywood': 1911,
         'top': 1911,
         'poor': 1897,
         'budget': 1894,
         'completely': 1889,
         'hand': 1889,
         'camera': 1888,
         'dead': 1881,
         'used': 1879,
         'either': 1866,
         'video': 1866,
         'given': 1849,
         'rest': 1836,
         'wrong': 1833,
         'head': 1832,
         'low': 1817,
         'writer': 1814,
         'couple': 1812,
         'enjoy': 1812,
         'word': 1811,
         'boring': 1809,
         'use': 1803,
         'full': 1780,
         'along': 1776,
         'kill': 1764,
         'truly': 1743,
         'run': 1731,
         'school': 1725,
         'awful': 1724,
         'hope': 1720,
         'next': 1716,
         'style': 1715,
         'sex': 1712,
         'mr': 1708,
         'remember': 1702,
         'stupid': 1701,
         'killer': 1700,
         'case': 1696,
         'person': 1686,
         'perhaps': 1681,
         'came': 1673,
         'brother': 1670,
         'title': 1669,
         'recommend': 1667,
         'sort': 1662,
         'wonderful': 1656,
         'dialogue': 1652,
         'small': 1647,
         'act': 1645,
         'understand': 1643,
         'terrible': 1638,
         'playing': 1633,
         'attempt': 1633,
         'getting': 1627,
         'fall': 1621,
         'game': 1621,
         'written': 1616,
         'flick': 1615,
         'care': 1613,
         'early': 1605,
         'sequence': 1603,
         'art': 1603,
         'often': 1601,
         'joke': 1600,
         'perfect': 1600,
         'others': 1595,
         'mother': 1593,
         'actress': 1588,
         'definitely': 1580,
         'review': 1566,
         'lost': 1554,
         'example': 1554,
         'cinema': 1553,
         'drama': 1552,
         'live': 1552,
         'white': 1546,
         'become': 1544,
         'feeling': 1540,
         'finally': 1536,
         'yes': 1535,
         'felt': 1528,
         'liked': 1516,
         'supposed': 1516,
         'waste': 1509,
         'quality': 1509,
         'son': 1506,
         'car': 1504,
         'absolutely': 1485,
         'begin': 1473,
         'worse': 1468,
         'evil': 1463,
         'heart': 1463,
         'went': 1463,
         'certainly': 1462,
         'entire': 1460,
         'direction': 1453,
         'oh': 1450,
         'entertaining': 1442,
         'overall': 1438,
         'feature': 1434,
         'side': 1434,
         'fight': 1433,
         'called': 1433,
         'comment': 1432,
         'based': 1430,
         'murder': 1430,
         'loved': 1428,
         'beginning': 1426,
         'lack': 1423,
         'several': 1420,
         'favorite': 1419,
         'number': 1409,
         'hero': 1388,
         'already': 1381,
         'dark': 1380,
         'becomes': 1380,
         'voice': 1374,
         'type': 1371,
         'michael': 1370,
         'age': 1370,
         'genre': 1367,
         'despite': 1364,
         'seemed': 1363,
         'throughout': 1360,
         'hit': 1360,
         'wanted': 1352,
         'unfortunately': 1352,
         'matter': 1351,
         'change': 1345,
         'meet': 1345,
         'b': 1339,
         'history': 1338,
         'final': 1336,
         'writing': 1332,
         'relationship': 1327,
         'fine': 1326,
         'close': 1323,
         'amazing': 1320,
         'town': 1318,
         'humor': 1317,
         'guess': 1315,
         'daughter': 1312,
         'cut': 1309,
         'totally': 1307,
         'event': 1283,
         'city': 1283,
         'today': 1282,
         'behind': 1280,
         'past': 1275,
         'god': 1271,
         'power': 1265,
         'experience': 1259,
         'able': 1259,
         'zombie': 1258,
         'move': 1257,
         'enjoyed': 1245,
         'stop': 1242,
         'theme': 1239,
         'soon': 1222,
         'sometimes': 1218,
         'gave': 1216,
         'stand': 1213,
         'etc': 1212,
         'late': 1211,
         'directed': 1204,
         'credit': 1204,
         'self': 1202,
         'horrible': 1201,
         'talent': 1201,
         'chance': 1200,
         'level': 1198,
         'brilliant': 1195,
         'body': 1190,
         'blood': 1186,
         'call': 1183,
         'stuff': 1181,
         'thinking': 1179,
         'expect': 1176,
         'element': 1175,
         'musical': 1167,
         'save': 1166,
         'question': 1164,
         'obviously': 1163,
         'wonder': 1163,
         'decent': 1157,
         'light': 1157,
         'situation': 1155,
         'add': 1147,
         'highly': 1147,
         'view': 1145,
         'lady': 1144,
         'group': 1142,
         'slow': 1131,
         'except': 1129,
         'novel': 1126,
         'score': 1121,
         'anyway': 1117,
         'interest': 1115,
         'career': 1114,
         'heard': 1111,
         'wish': 1111,
         'killed': 1111,
         'leave': 1107,
         'husband': 1105,
         'took': 1100,
         'dream': 1099,
         'police': 1098,
         'strong': 1096,
         'cannot': 1096,
         'rating': 1094,
         'robert': 1093,
         'violence': 1091,
         'country': 1086,
         'happens': 1080,
         'known': 1080,
         'particularly': 1079,
         'happened': 1076,
         'involved': 1076,
         'documentary': 1074,
         'extremely': 1069,
         'james': 1069,
         'obvious': 1066,
         'coming': 1065,
         'living': 1063,
         'told': 1063,
         'talk': 1062,
         'alone': 1061,
         'order': 1060,
         'theater': 1057,
         'including': 1052,
         'reality': 1050,
         'crap': 1049,
         'opinion': 1048,
         'effort': 1046,
         'thriller': 1046,
         'please': 1045,
         'room': 1044,
         'twist': 1043,
         'happen': 1043,
         'sequel': 1042,
         'gore': 1040,
         'king': 1037,
         'complete': 1035,
         'comic': 1034,
         'ago': 1033,
         'none': 1032,
         'hell': 1032,
         'david': 1025,
         'sister': 1025,
         'simple': 1023,
         'female': 1022,
         'ok': 1017,
         'rock': 1014,
         'looked': 1010,
         'season': 1010,
         'oscar': 1007,
         'seriously': 1002,
         'miss': 1001,
         'possible': 999,
         'class': 999,
         'annoying': 998,
         'sad': 996,
         'exactly': 995,
         'shown': 994,
         'running': 992,
         'value': 991,
         'serious': 989,
         'scary': 988,
         'released': 986,
         'taken': 986,
         'whose': 986,
         'english': 986,
         'cinematography': 983,
         'opening': 982,
         'usually': 981,
         'spoiler': 976,
         'deal': 975,
         'hilarious': 973,
         'cool': 971,
         'across': 971,
         'stay': 969,
         'street': 968,
         'somewhat': 965,
         'usual': 965,
         'happy': 965,
         'ridiculous': 964,
         'started': 963,
         'message': 960,
         'middle': 958,
         'tale': 956,
         'taking': 955,
         'mystery': 955,
         'talking': 954,
         'saying': 952,
         'figure': 949,
         'local': 947,
         'major': 946,
         'huge': 944,
         'mostly': 941,
         'single': 939,
         'five': 936,
         'jack': 933,
         'monster': 932,
         'important': 931,
         'modern': 931,
         'return': 931,
         'attention': 929,
         'george': 929,
         'earth': 929,
         'producer': 927,
         'strange': 926,
         'turned': 925,
         'open': 923,
         'cop': 921,
         'due': 918,
         'surprise': 918,
         'apparently': 917,
         'disappointed': 917,
         'four': 915,
         'dialog': 911,
         'television': 909,
         'future': 909,
         'result': 906,
         'basically': 906,
         'filmmaker': 900,
         'clearly': 899,
         'supporting': 899,
         'british': 898,
         'paul': 898,
         'non': 898,
         'knew': 897,
         'fast': 897,
         'mention': 896,
         'crime': 896,
         'hate': 893,
         'easily': 892,
         'cheap': 892,
         'silly': 888,
         'entertainment': 887,
         'dog': 887,
         'adult': 886,
         'release': 883,
         'team': 883,
         'parent': 881,
         'member': 879,
         'villain': 878,
         'break': 870,
         'bring': 869,
         'straight': 868,
         'state': 868,
         'beyond': 866,
         'form': 865,
         'animation': 864,
         'romantic': 863,
         'upon': 859,
         'whether': 856,
         'predictable': 854,
         'moving': 854,
         'peter': 853,
         'aspect': 852,
         'similar': 852,
         'ten': 851,
         'image': 851,
         'dance': 847,
         'richard': 847,
         'gun': 846,
         'hold': 845,
         'enjoyable': 842,
         'appears': 841,
         'note': 841,
         'giving': 840,
         'clich': 840,
         'doubt': 839,
         'viewing': 838,
         'within': 832,
         'red': 831,
         'killing': 826,
         'e': 825,
         'near': 824,
         'buy': 823,
         'present': 823,
         'storyline': 822,
         'working': 817,
         'bunch': 817,
         'lee': 817,
         'subject': 816,
         'dull': 816,
         'period': 815,
         'nearly': 815,
         'york': 811,
         'setting': 809,
         'standard': 803,
         'easy': 802,
         'using': 801,
         'surprised': 801,
         'named': 799,
         'fantastic': 798,
         'die': 794,
         'actual': 793,
         'victim': 793,
         'de': 792,
         'check': 792,
         'clear': 791,
         'french': 790,
         'material': 789,
         'showing': 786,
         'force': 786,
         'space': 786,
         'tom': 785,
         'stage': 785,
         'emotion': 785,
         'follow': 785,
         'general': 784,
         'among': 783,
         'typical': 778,
         'soundtrack': 778,
         'third': 776,
         'avoid': 775,
         'editing': 774,
         'tried': 773,
         'famous': 771,
         'sorry': 771,
         'soldier': 770,
         'baby': 769,
         'mark': 765,
         'certain': 764,
         'western': 764,
         'filmed': 763,
         'weak': 761,
         'realistic': 757,
         'somehow': 757,
         'disney': 756,
         'detail': 755,
         'gone': 754,
         'animal': 752,
         'wait': 752,
         'student': 752,
         'truth': 752,
         'battle': 750,
         'kept': 750,
         'cartoon': 750,
         'romance': 747,
         'premise': 746,
         'greatest': 745,
         'th': 745,
         'rent': 742,
         'lame': 742,
         'atmosphere': 741,
         'suspense': 739,
         'imagine': 737,
         'america': 737,
         'brought': 737,
         'screenplay': 735,
         'particular': 734,
         'hear': 733,
         'whatever': 732,
         'drug': 728,
         'male': 727,
         'fantasy': 725,
         'secret': 724,
         'walk': 724,
         'offer': 724,
         'nature': 723,
         'average': 723,
         'indeed': 722,
         'background': 720,
         'eventually': 720,
         'learn': 720,
         'forget': 716,
         'pay': 716,
         'adventure': 714,
         'japanese': 714,
         'poorly': 713,
         'believable': 711,
         'sexual': 710,
         'sit': 709,
         'possibly': 709,
         'society': 707,
         'okay': 706,
         'decided': 705,
         'issue': 705,
         'free': 705,
         'rate': 704,
         'expected': 704,
         'fit': 704,
         'leaf': 704,
         'reading': 703,
         'imdb': 702,
         'dr': 702,
         'escape': 701,
         'cause': 700,
         'choice': 699,
         'studio': 698,
         'masterpiece': 697,
         'became': 697,
         'difficult': 695,
         'doctor': 692,
         'focus': 691,
         'joe': 690,
         'match': 689,
         'accent': 688,
         'hot': 688,
         'lover': 688,
         'girlfriend': 684,
         'needed': 683,
         'beauty': 679,
         'development': 679,
         'touch': 678,
         'fire': 676,
         'unless': 675,
         'shame': 675,
         'box': 672,
         'forward': 672,
         'superb': 671,
         'bill': 671,
         'wood': 671,
         'otherwise': 670,
         'write': 670,
         'crazy': 670,
         'vampire': 668,
         'dramatic': 667,
         'memorable': 666,
         'copy': 665,
         'ghost': 665,
         'fear': 664,
         'award': 664,
         'weird': 664,
         'badly': 662,
         'week': 662,
         'earlier': 662,
         'cover': 661,
         'fi': 661,
         'mess': 661,
         'remake': 660,
         'forced': 660,
         'sci': 658,
         'acted': 658,
         'emotional': 657,
         'maker': 657,
         'cat': 657,
         'jane': 657,
         'footage': 656,
         'older': 656,
         'water': 655,
         'win': 655,
         'deep': 654,
         'realize': 654,
         'air': 652,
         'plus': 651,
         'spirit': 650,
         'interested': 650,
         'cry': 649,
         'ask': 648,
         'gay': 645,
         'directing': 644,
         'c': 643,
         'costume': 641,
         'quickly': 639,
         'business': 639,
         'creepy': 638,
         'towards': 637,
         'perfectly': 637,
         'party': 637,
         'era': 635,
         'co': 635,
         'worked': 635,
         'cheesy': 634,
         'unique': 634,
         'total': 632,
         'plenty': 632,
         'previous': 630,
         'brings': 630,
         'personal': 630,
         'christmas': 629,
         'incredibly': 626,
         'mistake': 626,
         'casting': 626,
         'plan': 625,
         'project': 623,
         'list': 623,
         'apart': 623,
         'leading': 622,
         'band': 622,
         'pick': 621,
         'admit': 621,
         'powerful': 620,
         'front': 620,
         'appear': 619,
         'ben': 617,
         'telling': 617,
         'potential': 616,
         'meant': 614,
         'la': 614,
         'hardly': 613,

In [19]:
cnt.most_common(10)

[('movie', 51694),
 ('film', 47034),
 ('one', 27741),
 ('like', 20740),
 ('time', 15959),
 ('good', 15197),
 ('character', 14177),
 ('story', 13165),
 ('even', 12646),
 ('get', 12514)]

In [20]:
# most Frequent words in both positive as well as negative reviews

pos_cnt = Counter("  ".join(train.loc[train['sentiment']==1]['clean_review'].tolist()).split())
neg_cnt = Counter("  ".join(train.loc[train['sentiment']==0]['clean_review'].tolist()).split())

In [21]:
print('Top 10 most common words across positive reviews')
print(pos_cnt.most_common(10))
print('-'*50)
print('Top 10 most common words across negative reviews')
print(neg_cnt.most_common(10))

Top 10 most common words across positive reviews
[('film', 24745), ('movie', 22657), ('one', 14169), ('like', 9270), ('time', 8346), ('good', 7762), ('story', 7478), ('character', 7073), ('well', 6488), ('great', 6435)]
--------------------------------------------------
Top 10 most common words across negative reviews
[('movie', 29037), ('film', 22289), ('one', 13572), ('like', 11470), ('even', 7684), ('time', 7613), ('good', 7435), ('bad', 7394), ('character', 7104), ('would', 7036)]

In [22]:
from wordcloud import WordCloud
import matplotlib.pyplot as plt

wordcloud = WordCloud(width=800, height=400, background_color='white').generate(" ".join(train['clean_review'].tolist()))

plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')  
plt.title("IMDB Movie Reviews Word Cloud")
plt.show()

ModuleNotFoundError: No module named 'wordcloud'

## Bag of Word Model

In [23]:
from sklearn.feature_extraction.text import CountVectorizer

In [24]:
x = train['clean_review']
y = train['sentiment']

In [25]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33, random_state = 42)

In [26]:
def create_vector(vectorizer, data):
    train_vector = vectorizer.transform(data.tolist())
    return train_vector.toarray()

In [27]:
vectorizer = CountVectorizer(max_features = 200)

In [28]:
vectorizer.fit(x_train.tolist())

CountVectorizer(max_features=200)

In [29]:
x_train_vector = create_vector(vectorizer, x_train)
x_test_vector = create_vector(vectorizer, x_test)

In [30]:
x_train_vector.shape

(16750, 200)

In [31]:
x_train_vector[0]

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [32]:
x_train[0]

'stuff going moment mj started listening music watching odd documentary watched wiz watched moonwalker maybe want get certain insight guy thought really cool eighty maybe make mind whether guilty innocent moonwalker part biography part feature film remember going see cinema originally released subtle message mj feeling towards press also obvious message drug bad kay visually impressive course michael jackson unless remotely like mj anyway going hate find boring may call mj egotist consenting making movie mj fan would say made fan true really nice actual feature film bit finally start minute excluding smooth criminal sequence joe pesci convincing psychopathic powerful drug lord want mj dead bad beyond mj overheard plan nah joe pesci character ranted wanted people know supplying drug etc dunno maybe hate mj music lot cool thing like mj turning car robot whole speed demon sequence also director must patience saint came filming kiddy bad sequence usually director hate working one kid let alone whole bunch performing complex dance scene bottom line movie people like mj one level another think people stay away try give wholesome message ironically mj bestest buddy movie girl michael jackson truly one talented people ever grace planet guilty well attention gave subject hmmm well know people different behind closed door know fact either extremely nice stupid guy one sickest liar hope latter'

In [33]:
 # Classical ML

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import * 
forest = RandomForestClassifier()
forest.fit(x_train_vector, y_train)

y_pred = forest.predict(x_test_vector)
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.74      0.76      0.75      4019
           1       0.76      0.75      0.76      4231

    accuracy                           0.75      8250
   macro avg       0.75      0.75      0.75      8250
weighted avg       0.75      0.75      0.75      8250

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf_vectorizer = TfidfVectorizer(analyzer = 'word', tokenizer = nltk.word_tokenize,
                               preprocessor = None, stop_words = 'english', max_features = 2000)
tf_vectorizer.fit(x_train.tolist())

x_train_tfvector = create_vector(tf_vectorizer, x_train)
x_test_tfvector = create_vector(tf_vectorizer, x_test)

x_test_tfvector.shape, x_train_tfvector.shape

C:\Users\karan\AppData\Roaming\Python\Python313\site-packages\sklearn\feature_extraction\text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

((8250, 2000), (16750, 2000))

In [35]:
forest = RandomForestClassifier()
forest.fit(x_train_tfvector, y_train)

y_pred = forest.predict(x_test_tfvector)
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.85      0.82      0.83      4221
           1       0.82      0.84      0.83      4029

    accuracy                           0.83      8250
   macro avg       0.83      0.83      0.83      8250
weighted avg       0.83      0.83      0.83      8250

In [36]:
y_pred

array([0, 1, 0, ..., 0, 0, 1], shape=(8250,))

In [37]:
# Create a model using Keras using TF-IDF
from keras.layers import Dense, Dropout, SimpleRNN
from keras.models import Sequential

model_ann = Sequential()

# Input layer with the number of features from X_train_tfvectoer
model_ann.add(Dense(units=128, activation='relu', input_shape=(x_train_tfvector.shape[1],)))
model_ann.add(Dropout(0.3))

model_ann.add(Dense(units=64, activation='relu'))
model_ann.add(Dropout(0.3))

model_ann.add(Dense(units=32, activation='relu'))
model_ann.add(Dropout(0.3))

# Output layer for binary classification
model_ann.add(Dense(units=1, activation='sigmoid'))

model_ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

history = model_ann.fit(
    x_train_tfvector,
    y_train,
    epochs=10,
    batch_size=32,
    validation_data=(x_test_tfvector, y_test)
)

C:\Users\karan\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8069 - loss: 0.4212 - val_accuracy: 0.8659 - val_loss: 0.3148
Epoch 2/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - accuracy: 0.8856 - loss: 0.2869 - val_accuracy: 0.8645 - val_loss: 0.3178
Epoch 3/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 9s 17ms/step - accuracy: 0.9131 - loss: 0.2319 - val_accuracy: 0.8613 - val_loss: 0.3354
Epoch 4/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 10s 15ms/step - accuracy: 0.9448 - loss: 0.1548 - val_accuracy: 0.8594 - val_loss: 0.3915
Epoch 5/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.9706 - loss: 0.0877 - val_accuracy: 0.8539 - val_loss: 0.4984
Epoch 6/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9837 - loss: 0.0493 - val_accuracy: 0.8521 - val_loss: 0.6574
Epoch 7/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.9860 - loss: 0.0405 - val_accuracy: 0.8498 - val_loss: 0.6687
Epoch 8/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.9890 - loss: 0.0335 - val_accuracy: 0.8513 - val_loss: 0.7274
Epoch 9/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.9924 - loss: 0.0229 - val_accuracy: 0.8519 - val_loss: 0.7930
Epoch 10/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9940 - loss: 0.0194 - val_accuracy: 0.8522 - val_loss: 0.8016

In [38]:
# Sample Data
# We will create our own word2vec model using this

sentences = [
    "The quick brown fox jumps over the lazy dog.",
    "Artificial intelligence is transforming the world we live in.",
    "Deep learning techniques have greatly improved image recognition.",
    "Natural language processing allows computers to understand human language.",
    "Data science combines statistics, computer science, and domain knowledge.",
    "The weather is nice today, perfect for a walk in the park.",
    "Cats are often seen as independent and curious creatures.",
    "The stock market fluctuates based on various economic indicators.",
    "Exploring new cuisines can be an exciting culinary adventure.",
    "Machine learning algorithms can learn from data and make predictions.",
]

In [39]:
!pip install gensim

Requirement already satisfied: gensim in c:\users\karan\anaconda3\lib\site-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in c:\users\karan\appdata\roaming\python\python313\site-packages (from gensim) (2.2.2)
Requirement already satisfied: scipy>=1.7.0 in c:\users\karan\appdata\roaming\python\python313\site-packages (from gensim) (1.16.0)
Requirement already satisfied: smart_open>=1.8.1 in c:\users\karan\anaconda3\lib\site-packages (from gensim) (7.6.1)
Requirement already satisfied: wrapt in c:\users\karan\anaconda3\lib\site-packages (from smart_open>=1.8.1->gensim) (1.17.0)

In [40]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('stopwords')

def preprocess_text(text):
    stop_words = set(stopwords.words('english'))
    tokens = word_tokenize(text.lower())
    tokens = [word for word in tokens if word.isalpha() and word not in stop_words]
    return tokens

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\karan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [41]:
def preprocess_text(text):
    stop_words = set(stopwords.words('english'))
    tokens = word_tokenize(text.lower())
    tokens = [word for word in tokens if word.isalpha() and word not in stop_words]
    return tokens

# Sample sentences with variety
sentences = [
    "The quick brown fox jumps over the lazy dog.",
    "Artificial intelligence is transforming the world we live in.",
    "Deep learning techniques have greatly improved image recognition.",
    "Natural language processing allows computers to understand human language.",
    "Data science combines statistics, computer science, and domain knowledge.",
    "The weather is nice today, perfect for a walk in the park.",
    "Cats are often seen as independent and curious creatures.",
    "The stock market fluctuates based on various economic indicators.",
    "Exploring new cuisines can be an exciting culinary adventure.",
    "Machine learning algorithms can learn from data and make predictions.",
]

# Preprocess sentences
preprocessed_sentences = [preprocess_text(sentence) for sentence in sentences]

In [42]:
from gensim.models import Word2Vec
model = Word2Vec(sentences =  preprocessed_sentences, vector_size = 100, window = 5, min_count = 1, workers = 4, sg = 1)

In [43]:
# Most similar word to machine

model.wv.most_similar('machine')

[('cats', 0.2851915657520294),
 ('world', 0.24013136327266693),
 ('language', 0.19946427643299103),
 ('natural', 0.19110660254955292),
 ('greatly', 0.1722787618637085),
 ('improved', 0.16694121062755585),
 ('jumps', 0.13812868297100067),
 ('transforming', 0.12715110182762146),
 ('human', 0.10051155090332031),
 ('fluctuates', 0.09709376841783524)]

In [47]:
# Lets use gensim downloader to download the pre trained model
import gensim.downloader

print(list(gensim.downloader.info()['models'].keys()))

glove_vectors = gensim.downloader.load('glove-twitter-25')

['fasttext-wiki-news-subwords-300', 'conceptnet-numberbatch-17-06-300', 'word2vec-ruscorpora-300', 'word2vec-google-news-300', 'glove-wiki-gigaword-50', 'glove-wiki-gigaword-100', 'glove-wiki-gigaword-200', 'glove-wiki-gigaword-300', 'glove-twitter-25', 'glove-twitter-50', 'glove-twitter-100', 'glove-twitter-200', '__testing_word2vec-matrix-synopsis']
[==================================================] 100.0% 104.8/104.8MB downloaded

In [49]:
glove_vectors.most_similar('machine')

[('maker', 0.9047849774360657),
 ('commercial', 0.8858075141906738),
 ('box', 0.8851054906845093),
 ('duty', 0.8844237327575684),
 ('range', 0.8840261101722717),
 ('speed', 0.8788419961929321),
 ('ink', 0.8769319653511047),
 ('table', 0.8757869005203247),
 ('piece', 0.8747599720954895),
 ('mask', 0.8721249103546143)]

In [44]:
# We will train our word2vec and use word2vec embeddings to train a classifier on IMDB Dataset
# We will use a pre trtained word2vec and use word2vec embeddings to train a classifier on IMDB Dataset

In [45]:
def get_pretrained_embeddings(tokenized_sentence, pretrained_model):
    word_vectors = [pretrained_model[word] for word in tokenized_sentence if word in pretrained_model.key_to_index]

    if word_vectors:
        return np.mean(word_vectors, axis=0)
    else:
        return np.zeros(pretrained_model.vector_size)

    return word_vectors

In [50]:
get_pretrained_embeddings(preprocessed_sentences[0], glove_vectors)

array([-5.47877848e-01, -7.66669691e-04,  4.06459957e-01,  4.87664975e-02,
        3.31105828e-01,  1.92321673e-01,  9.80231702e-01, -4.85084176e-01,
        2.12445006e-01, -1.88934997e-01,  1.24646686e-01,  1.94055006e-01,
       -3.25121665e+00, -4.99383330e-01,  1.89798310e-01, -9.47949886e-02,
        1.52681664e-01, -4.25679952e-01, -1.83547735e-01, -2.96628326e-01,
        2.52441674e-01,  3.32518667e-01,  6.86213315e-01, -4.06328321e-01,
       -3.50278430e-02], dtype=float32)

In [58]:
x_train_pretrained_glove = np.array(
    [get_pretrained_embeddings(review.split(), glove_vectors) for review in x_train]
)

In [59]:
x_test_pretrained_glove = np.array(
    [get_pretrained_embeddings(review.split(), glove_vectors) for review in x_test]
)

In [60]:
x_train_pretrained_glove.shape

(16750, 25)

In [61]:
x_test_pretrained_glove.shape

(8250, 25)

In [63]:
from keras.layers import Dense, Dropout, SimpleRNN
from keras.models import Sequential

model_ann = Sequential()

# Input layer with the number of features from X_train_tfvectoer
model_ann.add(Dense(units=128, activation='relu', input_shape=(x_train_pretrained_glove.shape[1],)))
model_ann.add(Dropout(0.3))

model_ann.add(Dense(units=64, activation='relu'))
model_ann.add(Dropout(0.3))

model_ann.add(Dense(units=32, activation='relu'))
model_ann.add(Dropout(0.3))

# Output layer for binary classification
model_ann.add(Dense(units=1, activation='sigmoid'))

model_ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

history = model_ann.fit(
    x_train_pretrained_glove,
    y_train,
    epochs=10,
    batch_size=32,
    validation_data=(x_test_pretrained_glove, y_test)
)

Epoch 1/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.6691 - loss: 0.6029 - val_accuracy: 0.7440 - val_loss: 0.5254
Epoch 2/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - accuracy: 0.7420 - loss: 0.5354 - val_accuracy: 0.7600 - val_loss: 0.5041
Epoch 3/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.7433 - loss: 0.5288 - val_accuracy: 0.7547 - val_loss: 0.5090
Epoch 4/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.7497 - loss: 0.5213 - val_accuracy: 0.7622 - val_loss: 0.4978
Epoch 5/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7479 - loss: 0.5203 - val_accuracy: 0.7619 - val_loss: 0.4977
Epoch 6/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.7502 - loss: 0.5191 - val_accuracy: 0.7476 - val_loss: 0.5136
Epoch 7/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - accuracy: 0.7497 - loss: 0.5171 - val_accuracy: 0.7589 - val_loss: 0.4987
Epoch 8/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.7523 - loss: 0.5141 - val_accuracy: 0.7593 - val_loss: 0.4964
Epoch 9/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.7511 - loss: 0.5171 - val_accuracy: 0.7616 - val_loss: 0.4947
Epoch 10/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7520 - loss: 0.5130 - val_accuracy: 0.7629 - val_loss: 0.4962

In [66]:
# Tokenize our training data of reviews

tokenized_review = train['clean_review'].apply(lambda x: x.split()).tolist()

In [68]:
tokenized_review[1:]

[['classic',
  'war',
  'world',
  'timothy',
  'hines',
  'entertaining',
  'film',
  'obviously',
  'go',
  'great',
  'effort',
  'length',
  'faithfully',
  'recreate',
  'h',
  'g',
  'well',
  'classic',
  'book',
  'mr',
  'hines',
  'succeeds',
  'watched',
  'film',
  'appreciated',
  'fact',
  'standard',
  'predictable',
  'hollywood',
  'fare',
  'come',
  'every',
  'year',
  'e',
  'g',
  'spielberg',
  'version',
  'tom',
  'cruise',
  'slightest',
  'resemblance',
  'book',
  'obviously',
  'everyone',
  'look',
  'different',
  'thing',
  'movie',
  'envision',
  'amateur',
  'critic',
  'look',
  'criticize',
  'everything',
  'others',
  'rate',
  'movie',
  'important',
  'base',
  'like',
  'entertained',
  'people',
  'never',
  'agree',
  'critic',
  'enjoyed',
  'effort',
  'mr',
  'hines',
  'put',
  'faithful',
  'h',
  'g',
  'well',
  'classic',
  'novel',
  'found',
  'entertaining',
  'made',
  'easy',
  'overlook',
  'critic',
  'perceive',
  'shortcoming'],
 ['film',
  'start',
  'manager',
  'nicholas',
  'bell',
  'giving',
  'welcome',
  'investor',
  'robert',
  'carradine',
  'primal',
  'park',
  'secret',
  'project',
  'mutating',
  'primal',
  'animal',
  'using',
  'fossilized',
  'dna',
  'like',
  'jurassik',
  'park',
  'scientist',
  'resurrect',
  'one',
  'nature',
  'fearsome',
  'predator',
  'sabretooth',
  'tiger',
  'smilodon',
  'scientific',
  'ambition',
  'turn',
  'deadly',
  'however',
  'high',
  'voltage',
  'fence',
  'opened',
  'creature',
  'escape',
  'begin',
  'savagely',
  'stalking',
  'prey',
  'human',
  'visitor',
  'tourist',
  'scientific',
  'meanwhile',
  'youngster',
  'enter',
  'restricted',
  'area',
  'security',
  'center',
  'attacked',
  'pack',
  'large',
  'pre',
  'historical',
  'animal',
  'deadlier',
  'bigger',
  'addition',
  'security',
  'agent',
  'stacy',
  'haiduk',
  'mate',
  'brian',
  'wimmer',
  'fight',
  'hardly',
  'carnivorous',
  'smilodons',
  'sabretooths',
  'course',
  'real',
  'star',
  'star',
  'astounding',
  'terrifyingly',
  'though',
  'convincing',
  'giant',
  'animal',
  'savagely',
  'stalking',
  'prey',
  'group',
  'run',
  'afoul',
  'fight',
  'one',
  'nature',
  'fearsome',
  'predator',
  'furthermore',
  'third',
  'sabretooth',
  'dangerous',
  'slow',
  'stalk',
  'victim',
  'movie',
  'delivers',
  'good',
  'lot',
  'blood',
  'gore',
  'beheading',
  'hair',
  'raising',
  'chill',
  'full',
  'scare',
  'sabretooths',
  'appear',
  'mediocre',
  'special',
  'effect',
  'story',
  'provides',
  'exciting',
  'stirring',
  'entertainment',
  'result',
  'quite',
  'boring',
  'giant',
  'animal',
  'majority',
  'made',
  'computer',
  'generator',
  'seem',
  'totally',
  'lousy',
  'middling',
  'performance',
  'though',
  'player',
  'reacting',
  'appropriately',
  'becoming',
  'food',
  'actor',
  'give',
  'vigorously',
  'physical',
  'performance',
  'dodging',
  'beast',
  'running',
  'bound',
  'leap',
  'dangling',
  'wall',
  'pack',
  'ridiculous',
  'final',
  'deadly',
  'scene',
  'small',
  'kid',
  'realistic',
  'gory',
  'violent',
  'attack',
  'scene',
  'film',
  'sabretooths',
  'smilodon',
  'following',
  'sabretooth',
  'james',
  'r',
  'hickox',
  'vanessa',
  'angel',
  'david',
  'keith',
  'john',
  'rhys',
  'davy',
  'much',
  'better',
  'bc',
  'roland',
  'emmerich',
  'steven',
  'strait',
  'cliff',
  'curtis',
  'camilla',
  'belle',
  'motion',
  'picture',
  'filled',
  'bloody',
  'moment',
  'badly',
  'directed',
  'george',
  'miller',
  'originality',
  'take',
  'many',
  'element',
  'previous',
  'film',
  'miller',
  'australian',
  'director',
  'usually',
  'working',
  'television',
  'tidal',
  'wave',
  'journey',
  'center',
  'earth',
  'many',
  'others',
  'occasionally',
  'cinema',
  'man',
  'snowy',
  'river',
  'zeus',
  'roxanne',
  'robinson',
  'crusoe',
  'rating',
  'average',
  'bottom',
  'barrel'],
 ['must',
  'assumed',
  'praised',
  'film',
  'greatest',
  'filmed',
  'opera',
  'ever',
  'read',
  'somewhere',
  'either',
  'care',
  'opera',
  'care',
  'wagner',
  'care',
  'anything',
  'except',
  'desire',
  'appear',
  'cultured',
  'either',
  'representation',
  'wagner',
  'swan',
  'song',
  'movie',
  'strike',
  'unmitigated',
  'disaster',
  'leaden',
  'reading',
  'score',
  'matched',
  'tricksy',
  'lugubrious',
  'realisation',
  'text',
  'questionable',
  'people',
  'idea',
  'opera',
  'matter',
  'play',
  'especially',
  'one',
  'shakespeare',
  'allowed',
  'anywhere',
  'near',
  'theatre',
  'film',
  'studio',
  'syberberg',
  'fashionably',
  'without',
  'smallest',
  'justification',
  'wagner',
  'text',
  'decided',
  'parsifal',
  'bisexual',
  'integration',
  'title',
  'character',
  'latter',
  'stage',
  'transmutes',
  'kind',
  'beatnik',
  'babe',
  'though',
  'one',
  'continues',
  'sing',
  'high',
  'tenor',
  'actor',
  'film',
  'singer',
  'get',
  'double',
  'dose',
  'armin',
  'jordan',
  'conductor',
  'seen',
  'face',
  'heard',
  'voice',
  'amfortas',
  'also',
  'appears',
  'monstrously',
  'double',
  'exposure',
  'kind',
  'batonzilla',
  'conductor',
  'ate',
  'monsalvat',
  'playing',
  'good',
  'friday',
  'music',
  'way',
  'transcendant',
  'loveliness',
  'nature',
  'represented',
  'scattering',
  'shopworn',
  'flaccid',
  'crocus',
  'stuck',
  'ill',
  'laid',
  'turf',
  'expedient',
  'baffle',
  'theatre',
  'sometimes',
  'piece',
  'imperfection',
  'thought',
  'think',
  'syberberg',
  'splice',
  'parsifal',
  'gurnemanz',
  'mountain',
  'pasture',
  'lush',
  'provided',
  'julie',
  'andrew',
  'sound',
  'music',
  'sound',
  'hard',
  'endure',
  'high',
  'voice',
  'trumpet',
  'particular',
  'possessing',
  'aural',
  'glare',
  'add',
  'another',
  'sort',
  'fatigue',
  'impatience',
  'uninspired',
  'conducting',
  'paralytic',
  'unfolding',
  'ritual',
  'someone',
  'another',
  'review',
  'mentioned',
  'bayreuth',
  'recording',
  'knappertsbusch',
  'though',
  'tempo',
  'often',
  'slow',
  'jordan',
  'altogether',
  'lack',
  'sense',
  'pulse',
  'feeling',
  'ebb',
  'flow',
  'music',
  'half',
  'century',
  'orchestral',
  'sound',
  'set',
  'modern',
  'pressing',
  'still',
  'superior',
  'film'],
 ['superbly',
  'trashy',
  'wondrously',
  'unpretentious',
  'exploitation',
  'hooray',
  'pre',
  'credit',
  'opening',
  'sequence',
  'somewhat',
  'give',
  'false',
  'impression',
  'dealing',
  'serious',
  'harrowing',
  'drama',
  'need',
  'fear',
  'barely',
  'ten',
  'minute',
  'later',
  'neck',
  'nonsensical',
  'chainsaw',
  'battle',
  'rough',
  'fist',
  'fight',
  'lurid',
  'dialog',
  'gratuitous',
  'nudity',
  'bo',
  'ingrid',
  'two',
  'orphaned',
  'sibling',
  'unusually',
  'close',
  'even',
  'slightly',
  'perverted',
  'relationship',
  'imagine',
  'playfully',
  'ripping',
  'towel',
  'cover',
  'sister',
  'naked',
  'body',
  'stare',
  'unshaven',
  'genitals',
  'several',
  'whole',
  'minute',
  'well',
  'bo',
  'sister',
  'judging',
  'dubbed',
  'laughter',
  'mind',
  'sick',
  'dude',
  'anyway',
  'kid',
  'fled',
  'russia',
  'parent',
  'nasty',
  'soldier',
  'brutally',
  'slaughtered',
  'mommy',
  'daddy',
  'friendly',
  'smuggler',
  'took',
  'custody',
  'however',
  'even',
  'raised',
  'trained',
  'bo',
  'ingrid',
  'expert',
  'smuggler',
  'actual',
  'plot',
  'lift',
  'year',
  'later',
  'facing',
  'ultimate',
  'quest',
  'mythical',
  'incredibly',
  'valuable',
  'white',
  'fire',
  'diamond',
  'coincidentally',
  'found',
  'mine',
  'thing',
  'life',
  'ever',
  'made',
  'little',
  'sense',
  'plot',
  'narrative',
  'structure',
  'white',
  'fire',
  'sure',
  'lot',
  'fun',
  'watch',
  'time',
  'clue',
  'beating',
  'cause',
  'bet',
  'actor',
  'understood',
  'even',
  'less',
  'whatever',
  'violence',
  'magnificently',
  'grotesque',
  'every',
  'single',
  'plot',
  'twist',
  'pleasingly',
  'retarded',
  'script',
  'go',
  'totally',
  'bonkers',
  'beyond',
  'repair',
  'suddenly',
  'reveal',
  'reason',
  'bo',
  'need',
  'replacement',
  'ingrid',
  'fred',
  'williamson',
  'enters',
  'scene',
  'big',
  'cigar',
  'mouth',
  'sleazy',
  'black',
  'finger',
  'local',
  'prostitute',
  'bo',
  'principal',
  'opponent',
  'italian',
  'chick',
  'big',
  'breast',
  'hideous',
  'accent',
  'preposterous',
  'catchy',
  'theme',
  'song',
  'play',
  'least',
  'dozen',
  'time',
  'throughout',
  'film',
  'obligatory',
  'falling',
  'love',
  'montage',
  'load',
  'attraction',
  'god',
  'brilliant',
  'experience',
  'original',
  'french',
  'title',
  'translates',
  'life',
  'survive',
  'uniquely',
  'appropriate',
  'make',
  'much',
  'sense',
  'rest',
  'movie',
  'none'],
 ['dont',
  'know',
  'people',
  'think',
  'bad',
  'movie',
  'got',
  'pretty',
  'good',
  'plot',
  'good',
  'action',
  'change',
  'location',
  'harry',
  'hurt',
  'either',
  'sure',
  'offensive',
  'gratuitous',
  'movie',
  'like',
  'eastwood',
  'good',
  'form',
  'dirty',
  'harry',
  'liked',
  'pat',
  'hingle',
  'movie',
  'small',
  'town',
  'cop',
  'liked',
  'dirty',
  'harry',
  'see',
  'one',
  'lot',
  'better',
  'dead',
  'pool'],
 ['movie',
  'could',
  'good',
  'come',
  'way',
  'short',
  'cheesy',
  'special',
  'effect',
  'acting',
  'could',
  'looked',
  'past',
  'story',
  'lousy',
  'background',
  'story',
  'would',
  'better',
  'plot',
  'center',
  'around',
  'evil',
  'druid',
  'witch',
  'linked',
  'woman',
  'get',
  'migraine',
  'movie',
  'drag',
  'never',
  'clearly',
  'explains',
  'anything',
  'keep',
  'plodding',
  'christopher',
  'walken',
  'part',
  'completely',
  'senseless',
  'movie',
  'movie',
  'potential',
  'look',
  'like',
  'really',
  'bad',
  'made',
  'tv',
  'movie',
  'would',
  'avoid',
  'movie'],
 ['watched',
  'video',
  'friend',
  'house',
  'glad',
  'waste',
  'money',
  'buying',
  'one',
  'video',
  'cover',
  'scene',
  'movie',
  'capricorn',
  'one',
  'movie',
  'start',
  'several',
  'clip',
  'rocket',
  'blow',
  'ups',
  'related',
  'manned',
  'flight',
  'sibrel',
  'smoking',
  'gun',
  'short',
  'video',
  'clip',
  'astronaut',
  'preparing',
  'video',
  'broadcast',
  'edits',
  'voice',
  'instead',
  'letting',
  'u',
  'listen',
  'crew',
  'say',
  'video',
  'curiously',
  'end',
  'showing',
  'zapruder',
  'film',
  'claim',
  'radiation',
  'shielding',
  'star',
  'photography',
  'others',
  'lead',
  'believe',
  'extremely',
  'ignorant',
  'sort',
  'ax',
  'grind',
  'nasa',
  'astronaut',
  'american',
  'general',
  'science',
  'bad',
  'video'],
 ['friend',
  'mine',
  'bought',
  'film',
  'even',
  'grossly',
  'overpriced',
  'despite',
  'featuring',
  'big',
  'name',
  'adam',
  'sandler',
  'billy',
  'bob',
  'thornton',
  'incredibly',
  'talented',
  'burt',
  'young',
  'film',
  'funny',
  'taking',
  'chisel',
  'hammering',
  'straight',
  'earhole',
  'us',
  'tired',
  'bottom',
  'barrel',
  'comedic',
  'technique',
  'consistently',
  'breaking',
  'fourth',
  'wall',
  'sandler',
  'talk',
  'audience',
  'seemingly',
  'pointless',
  'montage',
  'hot',
  'girl',
  'adam',
  'sandler',
  'play',
  'waiter',
  'cruise',
  'ship',
  'want',
  'make',
  'successful',
  'comedian',
  'order',
  'become',
  'successful',
  'woman',
  'ship',
  'resident',
  'comedian',
  'shamelessly',
  'named',
  'dickie',
  'due',
  'unfathomable',
  'success',
  'opposite',
  'gender',
  'presumed',
  'lost',
  'sea',
  'sandler',
  'character',
  'shecker',
  'get',
  'big',
  'break',
  'dickie',
  'dead',
  'rather',
  'locked',
  'bathroom',
  'presumably',
  'sea',
  'sick',
  'perhaps',
  'mouth',
  'vomited',
  'worst',
  'film',
  'time'],
 ['movie',
  'full',
  'reference',
  'like',
  'mad',
  'max',
  'ii',
  'wild',
  'one',
  'many',
  'others',
  'ladybug',
  'face',
  'clear',
  'reference',
  'tribute',
  'peter',
  'lorre',
  'movie',
  'masterpiece',
  'talk',
  'much',
  'future'],
 ['happens',
  'army',
  'wetback',
  'towelheads',
  'godless',
  'eastern',
  'european',
  'commie',
  'gather',
  'force',
  'south',
  'border',
  'gary',
  'busey',
  'kick',
  'butt',
  'course',
  'another',
  'laughable',
  'example',
  'reagan',
  'era',
  'cultural',
  'fallout',
  'bulletproof',
  'waste',
  'decent',
  'supporting',
  'cast',
  'headed',
  'l',
  'q',
  'jones',
  'thalmus',
  'rasulala'],
 ['although',
  'generally',
  'like',
  'remake',
  'believing',
  'remake',
  'waste',
  'time',
  'film',
  'exception',
  'actually',
  'know',
  'far',
  'reading',
  'previous',
  'comment',
  'remake',
  'opinion',
  'purely',
  'actual',
  'film',
  'comparison',
  'story',
  'way',
  'written',
  'question',
  'capote',
  'need',
  'word',
  'play',
  'anthony',
  'edward',
  'eric',
  'robert',
  'superb',
  'seen',
  'movie',
  'one',
  'certain',
  'good',
  'actor',
  'case',
  'eric',
  'always',
  'wondered',
  'sister',
  'number',
  'famous',
  'star',
  'brother',
  'time',
  'certainty',
  'raised',
  'fact',
  'question',
  'play',
  'well',
  'play',
  'mr',
  'edward',
  'clearly',
  'top',
  'profession',
  'recommend',
  'film',
  'top',
  'film',
  'see',
  'keep',
  'dvd',
  'shelf'],
 ['mr',
  'harvey',
  'light',
  'candle',
  'anchored',
  'brilliant',
  'performance',
  'timothy',
  'spall',
  'predict',
  'titular',
  'morose',
  'tight',
  'teacher',
  'sort',
  'break',
  'catharsis',
  'based',
  'deep',
  'secret',
  'past',
  'emotion',
  'unveiled',
  'surprising',
  'spall',
  'range',
  'feeling',
  'conveyed',
  'quite',
  'moving',
  'usually',
  'get',
  'portray',
  'part',
  'mike',
  'leigh',
  'repertory',
  'expected',
  'boring',
  'school',
  'bus',
  'trip',
  'used',
  'comic',
  'purpose',
  'simpson',
  'central',
  'situation',
  'visit',
  'salisbury',
  'cathedral',
  'rhidian',
  'brook',
  'script',
  'well',
  'contained',
  'structured',
  'dramatic',
  'purpose',
  'almost',
  'formally',
  'divided',
  'act',
  'introduced',
  'urban',
  'british',
  'range',
  'racially',
  'religiously',
  'diverse',
  'kid',
  'uniform',
  'tell',
  'private',
  'public',
  'school',
  'gather',
  'rapping',
  'black',
  'kid',
  'serious',
  'south',
  'asian',
  'muslim',
  'white',
  'bully',
  'mean',
  'girl',
  'conveyed',
  'quite',
  'naturally',
  'individually',
  'young',
  'actor',
  'recognized',
  'british',
  'tv',
  'shameless',
  'exuberant',
  'representing',
  'usual',
  'range',
  'junior',
  'high',
  'social',
  'pressure',
  'celia',
  'imrie',
  'put',
  'warmth',
  'supervisor',
  'role',
  'martinet',
  'usually',
  'play',
  'break',
  'trip',
  'lead',
  'transformative',
  'crisis',
  'others',
  'remain',
  'amusingly',
  'oblivious',
  'think',
  'like',
  'teacher',
  'portrayed',
  'ben',
  'mile',
  'coupling',
  'spoon',
  'fed',
  'didactic',
  'lesson',
  'religious',
  'tolerance',
  'much',
  'faith',
  'people',
  'well',
  'god',
  'bbc',
  'showed',
  'england',
  'easter',
  'time',
  'bbc',
  'america',
  'showed',
  'u',
  'christmas',
  'nathalie',
  'press',
  'also',
  'good',
  'summer',
  'love',
  'key',
  'role',
  'mr',
  'harvey',
  'redemption',
  'could',
  'played',
  'movie',
  'week',
  'preaching',
  'touching',
  'reach',
  'unexpected',
  'way',
  'unfortunately',
  'saw',
  'intense',
  'scene',
  'interrupted',
  'commercial',
  'bit',
  'heavy',
  'handed',
  'several',
  'time',
  'pointedly',
  'calling',
  'road',
  'trip',
  'pilgrimage',
  'quiet',
  'film',
  'best',
  'evocation',
  'good',
  'towards',
  'men',
  'seen',
  'holiday',
  'themed',
  'tv',
  'movie'],
 ['feeling',
  'submerged',
  'one',
  'better',
  'right',
  'must',
  'looking',
  'champagne',
  'money',
  'care',
  'final',
  'product',
  'voice',
  'get',
  'repeatedly',
  'dubbed',
  'stranger',
  'sound',
  'nothing',
  'like',
  'editing',
  'well',
  'grade',
  'amateurish',
  'nothing',
  'b',
  'c',
  'grade',
  'movie',
  'enough',
  'money',
  'hire',
  'couple',
  'talented',
  'cameraman',
  'ok',
  'sound',
  'designer',
  'like',
  'previous',
  'poster',
  'said',
  'problem',
  'seem',
  'appear',
  'post',
  'production',
  'voice',
  'dubbing',
  'etc',
  'bad',
  'cause',
  'plot',
  'actually',
  'ok',
  'sg',
  'flick',
  'never',
  'rent',
  'another',
  'sg',
  'flick',
  'unless',
  'email',
  'asking',
  'forgiveness',
  'bad',
  'miss',
  'kelly',
  'lebrock',
  'jimbo'],
 ['note',
  'george',
  'litman',
  'others',
  'mystery',
  'science',
  'theater',
  'riff',
  'think',
  'breeder',
  'favorite',
  'riff',
  'looking',
  'like',
  'simply',
  'complete',
  'absurdity',
  'right',
  'well',
  'would',
  'say',
  'must',
  'give',
  'credit',
  'mst',
  'k',
  'crew',
  'trying',
  'ridicule',
  'tv',
  'movie',
  'really',
  'make',
  'much',
  'fun',
  'dialog',
  'bill',
  'good',
  'playwright',
  'hand',
  'production',
  'bad',
  'even',
  'would',
  'disown',
  'junior',
  'high',
  'school',
  'drama',
  'club',
  'could',
  'better',
  'would',
  'recommend',
  'buy',
  'book',
  'read',
  'hamlet'],
 ['stephen',
  'king',
  'adaptation',
  'scripted',
  'king',
  'young',
  'family',
  'newcomer',
  'rural',
  'maine',
  'find',
  'pet',
  'cemetery',
  'close',
  'home',
  'father',
  'dale',
  'midkiff',
  'find',
  'micmac',
  'burial',
  'ground',
  'beyond',
  'pet',
  'cemetery',
  'power',
  'resurrection',
  'course',
  'anything',
  'buried',
  'come',
  'back',
  'quite',
  'right',
  'average',
  'horror',
  'picture',
  'start',
  'clumsy',
  'insulting',
  'inept',
  'continues',
  'way',
  'absolute',
  'worst',
  'element',
  'midkiff',
  'worthless',
  'performance',
  'get',
  'little',
  'better',
  'toward',
  'end',
  'genuinely',
  'disturbing',
  'finale',
  'point',
  'fact',
  'whole',
  'movie',
  'really',
  'disturbing',
  'completely',
  'dismiss',
  'least',
  'something',
  'make',
  'memorable',
  'decent',
  'supporting',
  'performance',
  'fred',
  'gwynne',
  'wise',
  'old',
  'aged',
  'neighbor',
  'brad',
  'greenquist',
  'disfigured',
  'spirit',
  'victor',
  'pascow',
  'enough',
  'really',
  'redeem',
  'film',
  'king',
  'usual',
  'cameo',
  'minister',
  'followed',
  'sequel',
  'also',
  'directed',
  'mary',
  'lambert',
  'wonder',
  'mainstream',
  'film',
  'work',
  'since'],
 ['matrix',
  'exciting',
  'summer',
  'blockbuster',
  'visually',
  'fantastic',
  'also',
  'curiously',
  'thought',
  'provoking',
  'twilight',
  'zone',
  'ish',
  'manner',
  'general',
  'rule',
  'applies',
  'sequel',
  'match',
  'predecessor',
  'worse',
  'even',
  'compare',
  'reloaded',
  'explodes',
  'onto',
  'screen',
  'un',
  'professional',
  'fashion',
  'opening',
  'second',
  'first',
  'impression',
  'generally',
  'good',
  'one',
  'trinity',
  'shot',
  'dream',
  'immediately',
  'film',
  'nose',
  'dive',
  'disastrous',
  'first',
  'minute',
  'gradually',
  'gain',
  'momentum',
  'enter',
  'matrix',
  'agent',
  'smith',
  'battle',
  'take',
  'place',
  'loses',
  'speed',
  'reach',
  'minute',
  'car',
  'chase',
  'sequence',
  'get',
  'even',
  'worse',
  'big',
  'groan',
  'worthy',
  'twist',
  'end',
  'worst',
  'overlong',
  'zion',
  'rave',
  'scene',
  'absolutely',
  'nothing',
  'plot',
  'also',
  'pathetic',
  'excuse',
  'porn',
  'depressive',
  'dance',
  'music',
  'bullet',
  'time',
  'aspect',
  'matrix',
  'good',
  'addition',
  'reloaded',
  'overuse',
  'make',
  'seem',
  'boring',
  'first',
  'one',
  'interesting',
  'plot',
  'turn',
  'linear',
  'remotely',
  'interesting',
  'movie',
  'basically',
  'series',
  'stylish',
  'diversion',
  'prevent',
  'u',
  'realising',
  'empty',
  'really',
  'work',

In [69]:
model_word2vec = Word2Vec(sentences =  tokenized_review, vector_size = 100, window = 5, min_count = 1, workers = 4, sg = 1)

In [70]:
model_word2vec.wv.most_similar('fox')

[('megan', 0.7260686755180359),
 ('eytan', 0.6713047027587891),
 ('nbc', 0.6554428935050964),
 ('lineup', 0.6524106860160828),
 ('twentieth', 0.6382241249084473),
 ('cub', 0.6330785155296326),
 ('cnn', 0.6295821070671082),
 ('cancellation', 0.6276618838310242),
 ('primetime', 0.6244731545448303),
 ('mulder', 0.6219335794448853)]

In [71]:
x_train_trained = np.array(
    [get_pretrained_embeddings(review.split(), model_word2vec.wv) for review in x_train]
)

x_test_trained = np.array(
    [get_pretrained_embeddings(review.split(), model_word2vec.wv) for review in x_test]
)

from keras.layers import Dense, Dropout, SimpleRNN
from keras.models import Sequential

model_ann = Sequential()

# Input layer with the number of features from X_train_tfvectoer
model_ann.add(Dense(units=128, activation='relu', input_shape=(x_train_trained.shape[1],)))
model_ann.add(Dropout(0.3))

model_ann.add(Dense(units=64, activation='relu'))
model_ann.add(Dropout(0.3))

model_ann.add(Dense(units=32, activation='relu'))
model_ann.add(Dropout(0.3))

# Output layer for binary classification
model_ann.add(Dense(units=1, activation='sigmoid'))

model_ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

history = model_ann.fit(
    x_train_trained,
    y_train,
    epochs=10,
    batch_size=32,
    validation_data=(x_test_trained, y_test)
)

Epoch 1/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.7666 - loss: 0.4773 - val_accuracy: 0.8579 - val_loss: 0.3337
Epoch 2/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.8423 - loss: 0.3728 - val_accuracy: 0.8582 - val_loss: 0.3321
Epoch 3/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.8487 - loss: 0.3562 - val_accuracy: 0.8624 - val_loss: 0.3206
Epoch 4/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.8524 - loss: 0.3498 - val_accuracy: 0.8617 - val_loss: 0.3174
Epoch 5/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.8552 - loss: 0.3474 - val_accuracy: 0.8594 - val_loss: 0.3224
Epoch 6/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.8590 - loss: 0.3391 - val_accuracy: 0.8674 - val_loss: 0.3107
Epoch 7/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 9s 16ms/step - accuracy: 0.8595 - loss: 0.3372 - val_accuracy: 0.8633 - val_loss: 0.3190
Epoch 8/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - accuracy: 0.8604 - loss: 0.3399 - val_accuracy: 0.8513 - val_loss: 0.3295
Epoch 9/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8577 - loss: 0.3364 - val_accuracy: 0.8578 - val_loss: 0.3223
Epoch 10/10
524/524 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.8593 - loss: 0.3357 - val_accuracy: 0.8638 - val_loss: 0.3155